### ISSUE TITLE
Error occurred

### ISSUE THREAD

**Issue by BlueNightSky** [teelolws/TLDRMissions#1]
The following error occurred, using the latest version:
(another little suggestion, can join the resource treasure chest option in the priority？)
`1x TLDRMissions\simulation.lua:531: attempt to index local 'rngTargets' (a nil value)
[string "@TLDRMissions\simulation.lua"]:531: in function <TLDRMissions\simulation.lua:485>
[string "@TLDRMissions\simulation.lua"]:929: in function <TLDRMissions\simulation.lua:908>
[string "@TLDRMissions\simulation.lua"]:977: in function <TLDRMissions\simulation.lua:966>
[string "@TLDRMissions\simulation.lua"]:1380: in function `turnRecursion'
[string "@TLDRMissions\simulation.lua"]:1396: in function <TLDRMissions\simulation.lua:27>
[string "@TLDRMissions\simulation.lua"]:1567: in function `Simulate'
[string "@TLDRMissions\combinations.lua"]:7: in function `func'
[string "@TLDRMissions\workhandler.lua"]:38: in function <TLDRMissions\workhandler.lua:23>

Locals:
follower = <table> {
 name = "淵喉"
 boardIndex = 13
 baseAttack = 100
 buffs = <table> {
 }
 changeDamageDealtPercent = 100
 changeDamageDealtRaw = 0
}
targetType = "random_ally"
rngTargets = nil
overrideTarget = nil
targets = <table> {
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
}
(for control) = 1
_ = 1
minion = <table> {
 autoAttack = <table> {
 }
 maxHP = 3900
 changeDamageDealtRaw = 0
 spells = <table> {
 }
 changeDamageDealtPercent = 100
 boardIndex = 10
 changeDamageTakenPercent = 100
 changeDamageTakenRaw = 0
 name = "多羅斯"
 followerID = -1
 baseAttack = 195
 buffs = <table> {
 }
 HP = 3900
 thorns = <table> {
 }
}
(*temporary) = 10
(*temporary) = <table> {
 autoAttack = <table> {
 }
 maxHP = 3900
 changeDamageDealtRaw = 0
 spells = <table> {
 }
 changeDamageDealtPercent = 100
 boardIndex = 10
 changeDamageTakenPercent = 100
 changeDamageTakenRaw = 0
 name = "多羅斯"
 followerID = -1
 baseAttack = 195
 buffs = <table> {
 }
 HP = 3900
 thorns = <table> {
 }
}
(*temporary) = nil
(*temporary) = "attempt to index local 'rngTargets' (a nil value)"
getClosestEnemy = <function> defined @TLDRMissions\simulation.lua:92
getAllEnemies = <function> defined @TLDRMissions\simulation.lua:429
getBackEnemies = <function> defined @TLDRMissions\simulation.lua:376
getFrontEnemies = <function> defined @TLDRMissions\simulation.lua:348
getCleaveEnemies = <function> defined @TLDRMissions\simulation.lua:124
getLineEnemies = <function> defined @TLDRMissions\simulation.lua:239
getConeEnemies = <function> defined @TLDRMissions\simulation.lua:280
getFurthestEnemy = <function> defined @TLDRMissions\simulation.lua:177
print = <function> defined @TLDRMissions\simulation.lua:6
field = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
}
getAllAllies = <function> defined @TLDRMissions\simulation.lua:417
getClosestAlly = <function> defined @TLDRMissions\simulation.lua:207
getAdjacentAllies = <function> defined @TLDRMissions\simulation.lua:318
getOtherAllies = <function> defined @TLDRMissions\simulation.lua:405
getFrontAllies = <function> defined @TLDRMissions\simulation.lua:441
getBackAllies = <function> defined @TLDRMissions\simulation.lua:467
`

**Comment by teelolws** [comment]
The environment effect 229 "Mawsworn Ritual" wasn't programmed properly. Should be fixed now in 9.2-008
