### ISSUE TITLE
[BUG] Specific mission is not being sent out

### ISSUE THREAD

**Issue by zeenk** [teelolws/TLDRMissions#101]
I noticed that this mission https://www.wowhead.com/mission=2270/baron-halis
was not being sent out after calculations were done on 2 of my alts today even tho I have many followers left that can easily beat it with VenturePlan, maybe some kind of bug with it?

**Comment by teelolws** [comment]
Do you mean it can't calculate a solution for it at all, or do you mean its giving a list of followers+troops for it, but the Start Mission button isn't working properly?

I found an issue with the Start Mission system last night, which is going up in the next patch.

**Comment by zeenk** [comment]
I'm gonna check if I get this mission again later tonight when I do my missions, maybe I accidentally skipped it without paying attention to it. Just was weird that it happened twice. I'll report back in a couple of hours.

**Comment by teelolws** [comment]
I was having an issue with it prompting the same mission twice or three times when you'd already started it. Theres a problem somewhere with it reporting a successful mission that it already reported successful with a different permutation. I haven't been able to find the cause but I at least treated the symptoms: it won't add a mission to the Start Mission queue that is already in the queue.
