### ISSUE TITLE
[BUG] Calculation bug

### ISSUE THREAD

**Issue by zeenk** [teelolws/TLDRMissions#103]
![2022-04-28_05-06-20](https://user-images.githubusercontent.com/68170439/165668606-fc4d5176-625a-45d1-afca-b7eaf00c045d.png)

Says it's calculating but doesn't say for which mission. (bug happened after I sent some missions and still had some left to send out)

**Comment by teelolws** [comment]
Yeah I was having problems with it naming the wrong mission there. I haven't been able to solve that bug yet so in the meantime I just replaced it with "Calculating...". guihandler.lua is some nasty spaghetti code that even I have lost track of now.

**Comment by zeenk** [comment]
Ah okay

**Comment by zeenk** [comment]
![2022-04-28_05-34-01](https://user-images.githubusercontent.com/68170439/165671077-56a7aa9a-36da-4121-a445-aa51d58d382a.png)
Another bug? Not able to hit start mission after the simulations were completed.

**Comment by teelolws** [comment]
Hmm. Its not showing the rewards either.

Did it already send the mission but the text didn't go away?

**Comment by zeenk** [comment]
Nope, didn't send any mission named that and it's not in my mission list

**Comment by teelolws** [comment]
Maybe the mission was in the list when it started calculations, but for whatever reason, Blizzard took the mission away before you sent it? Maybe the time limit ran out?

**Comment by zeenk** [comment]
Could be a possibility, Gonna do the rest of my missions and see if it happens again.

**Comment by teelolws** [comment]
According to the page: https://www.wowhead.com/mission=2225/corpselice-spawnlings it has a 7 hour timelimit, so its entirely possible it timed out during that window.

**Comment by zeenk** [comment]
![2022-04-28_05-41-08](https://user-images.githubusercontent.com/68170439/165671840-84971629-9cf8-429c-95e5-13d4eb8c2f82.png)

The bug report I made earlier about this mission must had been an accidental skip on my part because it showed up now.

**Comment by teelolws** [comment]
Was wondering if I could make it put a message if a mission is going to expire in less than 10 minutes, but it might not be easy to detect that. The data Blizzard gives is:

           offerTimeRemaining = "6h 27min",

Why oh why couldn't they give me that as a number in seconds :(

**Comment by teelolws** [comment]
UI getting really compressed and yucky now

![image](https://user-images.githubusercontent.com/49792789/165676364-41947580-c9c8-4e24-97e3-d279c59d813e.png)

It needs to be < 10min for that to actually show, I just didn't want to wait another 6 minutes to show an example.

**Comment by zeenk** [comment]
Yeah I think it was just a very unlucky timing on that other screenshot with not being able to start the mission, has not happened on any of my other chars so far.

**Comment by zeenk** [comment]
![2022-04-28_20-30-38](https://user-images.githubusercontent.com/68170439/165822301-7d29fa6c-a7fc-44e2-adb6-7ad99512fbd4.png)
Another weird bug lol, I can hit start mission but doesn't show reward or mission name 🤔

**Comment by zeenk** [comment]
This blank info bug happened again now on another alt and when I clicked start mission it sent out this mission https://www.wowhead.com/mission=2339/mawsworn-invaders don't know if it only bugging out for this specific mission or it's just a random bug, the information for next mission came back after the mission with no information was sent out.

**Comment by teelolws** [comment]
I don't know whats causing this. Did you install todays patch?

**Comment by zeenk** [comment]
I was using the latest update ye but it only happened on 3 out of 44 alts maybe clicking the start mission button to fast causing it to bug out? Not sure.

**Comment by teelolws** [comment]
I put delays on when the Start Mission button is available again to stop this happening. I wonder that maybe its interference from another addon. Going to try with VP and CMH turned on, see if I can make it happen.

**Comment by zeenk** [comment]
I disable unessary addons I don't need while doing my missions for faster loading screens, the only missions I'm running is: auctionator, bagnon, in progress missions, postal, tldr nussions, venture plan, weakauras, tsm. But I don't remember seeing this bug before so must have started in last 2-3 days maybe? I'm gonna try see if I can reproduce it.

**Comment by teelolws** [comment]
So what I did was I made it clear the text (though I clearly forgot to make it clear the anima cost text) when you click that Start Mission button, then it waits for Blizzard to send a message back saying the mission was sent before it fills anything. I don't know why the button is re-enabling without filling in any text. I need to get it to happen to me so I can figure it out.

**Comment by zeenk** [comment]
I have it disabled yea, I'll turn it on when I do my missions again next time and see if I get any lua errors.

**Comment by zeenk** [comment]
Hmm it just happened again and I noticed this mission https://www.wowhead.com/mission=2207/respite-from-the-darkness was the first mission in the start mission queue this time as well once this mission got sent the other one was blank (same as in the video) 🤔

**Comment by teelolws** [comment]
Hmm you can see it briefly popup the next mission then disappear, probably wiped the text when it got the event back from Blizzard. But why is it popping the next missions text early, not meant to do that.

**Comment by teelolws** [comment]
A tiny change to the order of how that button is handled. Can you try this?

[guihandlers.zip](https://github.com/teelolws/TLDRMissions/files/8594413/guihandlers.zip)

**Comment by zeenk** [comment]
I will try it next time I do my misions so in around 6 hours ish

**Comment by teelolws** [comment]
Nvm it didn't work. I've finally been able to reproduce the problem.

**Comment by zeenk** [comment]
No failed missions and no weird bugs today when I used the latest version of the addon, did u manage to find the issue with the blank mission bug? also do you still want these "Devtesting Discrepancy for mission x" reports?

**Comment by teelolws** [comment]
Time will tell with the blank mission bugs! Its an obscure case when a result comes in right as you're clicking the button to send a mission.

As for the DevTesting stuff, at this point, only for missions that aren't one of the ones I have separate threads about. Those "randomness" missions will ALWAYS have discrepancies, because, well, they're random. But non-random missions, if theres a discrepancy, I need to know.

**Comment by zeenk** [comment]
Alright, I'll check tomorrow if I get any new ones that aren't on the list already ^^
