### ISSUE TITLE
Test case: are equal mission IDs still the same mission?

### ISSUE THREAD

**Issue by teelolws** [teelolws/TLDRMissions#106]
Find two characters with the same mission, see if all the enemies are exactly the same.

**Comment by zeenk** [comment]
![2022-04-28_19-02-34](https://user-images.githubusercontent.com/68170439/165806264-3e2f3925-8bd8-4382-9dbc-4e66229f75e1.png)
![2022-04-28_19-04-09](https://user-images.githubusercontent.com/68170439/165806270-909cabd9-0eed-4df3-b3f9-57124d36d119.png)
Looks like it

**Comment by teelolws** [comment]
Not quite.

![image](https://user-images.githubusercontent.com/49792789/165844211-fa4de211-deb9-4643-87cf-3fa2054fe1b8.png)

**Comment by zeenk** [comment]
hmm guess it depends on your table campaign level or follower lvls?

**Comment by teelolws** [comment]
Yes. But it means my account-wide cache in its current state is invalid. I need to further index the missions by their scaled level.

**Comment by teelolws** [comment]
done in next patch
