### ISSUE TITLE
Sanctum Feature Category

### ISSUE THREAD

**Issue by Fenikxs** [teelolws/TLDRMissions#109]
**TLDR Version of your idea**
TLDR version: Adding new type of mission - seeds that are used in Queen's Conservatory building for Night Fea.

**Slightly longer version**
Type of seeds that we can get from the missions:
https://www.wowhead.com/item=178883/greater-prideful-spirit
https://www.wowhead.com/item=177699/greater-untamed-spirit
https://www.wowhead.com/item=178877/greater-martial-spirit
https://www.wowhead.com/item=178880/greater-dutiful-spirit

**Comment by teelolws** [comment]
I was going to go with a more generic category like "junk for your sanctum feature", so it can include the stichings for necrolords, the skyplumes or whatever for kyrian, and venthyr get random weird profession items that are needed for their RSVP quests.

Once I add that, basically every reward is in a category by that point, and the catch-all option can be removed.
