### ISSUE TITLE
Feature to skip white/green material caches

### ISSUE THREAD

**Issue by Fenikxs** [teelolws/TLDRMissions#110]
**TLDR Version of your idea**
TLDR version: Option to select quality of material caches or option to skip white/green.

**Slightly longer version**
Right now addon trying to send also mission for white/green material caches. They are useless, will be great if we can limit somehow to only get blue caches. Example mission with blue caches:
https://www.wowhead.com/mission=2193/brittlebark-manifestations

**Comment by teelolws** [comment]
Same request as: https://github.com/teelolws/TLDRMissions/issues/107
