### ISSUE TITLE
[BUG] Coalescing Stygia Mission

### ISSUE THREAD

**Issue by zaphon** [teelolws/TLDRMissions#114]
So it appears the missions (such as the one above) that reward Condensed Stygia don't have a category. Even if I select every option it won't consider this mission (right now I have everything selected but Equipment). Not sure where the proper place to put that is, but just wanted to give you a heads up.

**Comment by teelolws** [comment]
My mistake. All the Stygia missions I checked had other rewards, so a mission with only Stygia got missed. I'll put it under Runecarver rewards.

**Comment by teelolws** [comment]
Making it off by default cause who really wants Stygia anymore?

![image](https://user-images.githubusercontent.com/49792789/166064128-0c1562b5-110a-4d21-8b05-2751a27d15a0.png)

**Comment by zaphon** [comment]
Sounds good!
