### ISSUE TITLE
One button do it all

### ISSUE THREAD

**Issue by forwowaddons** [teelolws/TLDRMissions#115]
**TLDR Version of your idea**
TLDR version:  One button do it all

**Slightly longer version**
Would it be possible to get a button that functions the same as the finish all missions but to also batch start all the missions? This could also be combined with the finish missions first. Obviously this would take into account other settings.

**Comment by czullo** [comment]
i was thinking about same thing, like if you hit TLDR button addon will finish all missions and send new ones.

**Comment by teelolws** [comment]
An "auto start" button has been on my radar since the start of the project, but I don't want to add it until I have more confidence in all the other parts of the addon.

**Comment by teelolws** [comment]
Done.
