### ISSUE TITLE
[BUG] Campaign quests with items

### ISSUE THREAD

**Issue by forwowaddons** [teelolws/TLDRMissions#118]
![image](https://user-images.githubusercontent.com/104635425/166077031-7f58654c-b945-4b27-b525-8b97c52ae40f.png)

Seems like it doesnt start campaign missions if there's a piece of gear in it as well. Is this fixable?

**Comment by teelolws** [comment]
This is by design. Exclusions have priority. Just uncheck the Equipment button completely, no tick, no cross, and it'll send the mission that has both Campaign and Equipment as a reward.

**Comment by forwowaddons** [comment]
Wont it also send out missions with only gear then? I want to avoid that

**Comment by teelolws** [comment]
- A cross: it won't send a mission with this, no matter what
- A tick: it will send a mission with this, unless that mission also has something you marked with a across
- No tick or cross: it wont send this mission, unless it has another reward that you marked with a tick

**Comment by forwowaddons** [comment]
That makes sense, thanks!
