### ISSUE TITLE
Account-wide OR Exportable Settings 

### ISSUE THREAD

**Issue by lgkern** [teelolws/TLDRMissions#121]
**TLDR Version of your idea**
Have settings for the addon be account-wide or able to import/export them via string.

**Additional context**
Right now it takes a really long time to set up settings on every character. The situation worsens with new settings being added, which sucks, because the new settings are great, but having to reconfigure them on 50+ characters is annoying.

**Comment by teelolws** [comment]
If I do this, other players will complain that they wanted their settings to be character-specific, and I can't please everyone. You can copy your settings over by copying the character specific saved variables to the new character.

**Comment by lgkern** [comment]
Could you add then the ability to import/export settings via string? That would make the process of setting up new characters way faster and even allow people to share 'profiles' for faster leveling or goldmaking.

**Comment by teelolws** [comment]
I'll consider it.

**Comment by teelolws** [comment]
Profiles in next patch.
