### ISSUE TITLE
[BUG] campaign mission 

### ISSUE THREAD

**Issue by L30m4nc3r** [teelolws/TLDRMissions#126]
![image](https://user-images.githubusercontent.com/710285/166114021-b422c3fa-fe8d-41ed-85b3-33bfcacc8d3b.png)
All the time he offers to make a campaign mission, all the time you have to monitor this so as not to accidentally send it to the task, so I've already pumped one table and now I can't complete tasks there. Maybe it's due to the language barrier? 

On russian Campaign = Кампания

**Comment by L30m4nc3r** [comment]
ah sorry now its work i think.
![image](https://user-images.githubusercontent.com/710285/166114234-a671f5b1-c404-43ee-b36b-2fb81bd0acda.png)

**Comment by teelolws** [comment]
Yes, thats what the Xs are for. X means "don't send any mission that has this", and it has priority over everything else for missions with >1 reward.
