### ISSUE TITLE
[BUG] Addon seem awfully slow

### ISSUE THREAD

**Issue by forwowaddons** [teelolws/TLDRMissions#133]
Seems like the addon is very slow after the last update. Both in terms of actually starting missions and calculating.

**Comment by teelolws** [comment]
Starting missions now has a delay. You can thank Blizzard for this for sending the wrong followers on missions. I've had to add a delay where the addon checks the right followers are assigned before sending them.

Calculating hasn't changed. It should be just as slow as it was before! Its all about how hard the mission is. If it has "random enemy" or "random ally" spells its going to take a long time, cause it has to test every possibility.

**Comment by forwowaddons** [comment]
Alright so its by design, good to know. Really looking forward to that do it all one button, since right now it's way slower than before. appreciate what you are doing with this addon, wouldnt even be running the mission table without it.

**Comment by teelolws** [comment]
I probably won't do "all in one" in the way you're imagining. It would be more like "auto send" or something. Send the missions once they're calculated. I wouldn't have it auto start calculating as soon as you open it - cause then I'll have a wave of players complaining they never got a chance to change the setting or stop it.

**Comment by forwowaddons** [comment]
Yes but that's a great option as well, just a way to send out the missions with as few clicks as possible based on personal settings.
