### ISSUE TITLE
[BUG] button doesn't show

### ISSUE THREAD

**Issue by Maycke25** [teelolws/TLDRMissions#143]
the button to open the addon screen does not show on the quest table if you have the War plan addon enabled
https://www.curseforge.com/wow/addons/war-plan

to replicate
install TLDR and War plan
open the shadowlands quest table, the button will not be there
deactivate the War plan and the button will appear

I don't know who's to blame for not showing up
I loved your addon, congratulations
have a nice day

edit: sorry for google translate english

**Comment by teelolws** [comment]
Fixed next patch.
