### ISSUE TITLE
Will it BAN us?

### ISSUE THREAD

**Issue by MightyFirst** [teelolws/TLDRMissions#146]
Please remove "Immediately start missions once calculated". This is automation that could bring bans to users of this addon. 
Player no longer makes decision to start mission with chosen followers. Instead addon plays game (mission table) without player.

**Comment by teelolws** [comment]
Blizzard have said for a long time, "if its possible with just addons, you won't get banned". If they don't like it, they'll lock the Start Mission function behind a keypress.

**Comment by Nillx** [comment]
Blizz never banned anyone for using addons, if they dont like it they hotfix disable it.
