### ISSUE TITLE
Upload to other addon hosting sites

### ISSUE THREAD

**Issue by marthammor** [teelolws/TLDRMissions#148]
Hello.
I'm assuming you have a hidden repo for the code so you can still make some revenue off hosting this through Curse, which is great.
I'd like to ask you to also consider hosting it on other sites like wago.io as well, which would still allow you to gain revenue while allowing us who don't want to deal with Overwolf/Curse to still support your addons.
A package manager such as the one from BigWigs [https://github.com/BigWigsMods/packager](https://github.com/BigWigsMods/packager) would make it easier for you to upload to multiple places easily.
Thank you for your time.

**Comment by teelolws** [comment]
I do not agree to the terms and conditions required to host on wago.io.

**Comment by tflo** [comment]
Would [WoWUp Hub](https://wowup.io/guide/wowup/hub) be an alternative?

No revenues from there, but since – I think – most of the WoWUp users don’t touch the Overwolf client anyway, that would be a negligible loss. 

So, at least the WoWUp users would continue to get automatic updates.
