### ISSUE TITLE
[BUG] Huge chat spam with 9.2-044 patch

### ISSUE THREAD

**Issue by zeenk** [teelolws/TLDRMissions#157]
![2022-05-08_04-33-27](https://user-images.githubusercontent.com/68170439/167279308-0d3f94b7-fa5d-4e2d-8694-e4d8476cfcb4.png)

Happened while calculating these missions on Venthyr so far! https://www.wowhead.com/mission=2301/learn-from-the-master 
https://www.wowhead.com/mission=2308/nimble-scavengers
https://www.wowhead.com/mission=2346/stablizing-the-geomentals

Didn't give any lua errors.
(Has only happened on venthyr characters so far, I'm skipping these mission in case  they are bugged and sending them out with venture plan instead.)

**Comment by teelolws** [comment]
Gdi, I tested it on 5 characters before I published but didn't trip this. I know what the problem is. I moved the targetting code to a new file, which doesn't have my separate `print` handler.

**Comment by zeenk** [comment]
Is it something I should worry about or will it still calculate the missions correctly?

**Comment by teelolws** [comment]
They'll calculate correctly, its just putting those messages into your chat when its supposed to discard them completely. They're messages meant for the program I use to test the Simulator outside of WoW.

**Comment by zeenk** [comment]
Oh okay, phew.

**Comment by teelolws** [comment]
It'll be happening on Venthyr because of Najdia or whatever the name is. The minion that goes into Stealth for 2 turns. That means 2 turns where the enemies can't target anything.

**Comment by zeenk** [comment]
I see, thx for letting me know ^^

**Comment by teelolws** [comment]
![image](https://user-images.githubusercontent.com/49792789/167280070-9909765f-0a88-4360-a9db-4a46d7226910.png)
 that ability has been responsible for about half the missions you've reported lol. Its the only follower with it, and causes the targetting to do weird things.

**Comment by zeenk** [comment]
Sneaky bastard

**Comment by teelolws** [comment]
Ok 045 is up whenever curseforge approves it.

**Comment by zeenk** [comment]
Could you upload the fix here meanwhile? im doing my missions atm :P

**Comment by teelolws** [comment]
Yeah they usually take between 2 and 10min to approve it. On Thursday one of them tripped over a cable and turned automatic approval off, which was annoying. I hosted the file here when I realised what happened until they approve it manually.
