### ISSUE TITLE
Strangely Venthyr missions least likely to solve quickly...

### ISSUE THREAD

**Issue by dilvishdamned** [teelolws/TLDRMissions#158]
Across my 5 max lvl alts, 3 Ardenweald, 1 Maldraxxus, 1 Venthyr covenants.  Been using your addon for about a week & doing decent job (although some missions DO fail)...having an issue on Venthyr with MASSIVE amount of simulations running to solve very simple gold missions (I usually manually win those with 210 damage adventurers (the lowest besides that 1 Maldraxxus abomination who has 140 damage, but I digress that is a different covenant)).  As of writing this, the addon is still running at well above 149,000 simulations.  Cancelling at any time & starting over does not help.  
![image](https://user-images.githubusercontent.com/60253285/167288113-1d9a670a-4901-4b5f-aef9-393fcf27afc1.png)

**Comment by teelolws** [comment]
Its not Venthyr, its the mission. Gorging Anima Theives. I have an issue open for that mission: https://github.com/teelolws/TLDRMissions/issues/87 and I'm actively collecting logs for that mission to find a way to solve that mission more quickly.

The enemy minions cast Anima Leech at themselves (lol) and its on my list to find a pattern to which one they always target, so the addon won't have to test every possibility.

**Comment by dilvishdamned** [comment]
Awesome, thank you for the fast response!  At least I wasn't going crazy (those missions do have a lot of health too)!
