### ISSUE TITLE
[BUG] Ignores campaing mission progress on russian locale

### ISSUE THREAD

**Issue by SappFire2008** [teelolws/TLDRMissions#159]
Can it be due having zero currency or VenturePlan?
![ignore](https://user-images.githubusercontent.com/105151052/167290881-b46259e4-d92f-4305-b4fd-223ccd95e6a1.png)
![settings](https://user-images.githubusercontent.com/105151052/167290884-32130e10-bda6-47bb-80e3-f13c79a720be.png)

**Comment by teelolws** [comment]
> No followers in your restrictions are available.

Do you have any followers (that aren't already on missions) that are level 9 or higher?

**Comment by SappFire2008** [comment]
Oh, kinda got it why it ignored. 
No, didn't have any of lvl 9 at that moment. Checked on another toon, where it flashed while calculating, so it surely works. So my fault

**Comment by teelolws** [comment]
Bump the level limit up, it'll probably still beat the mission with level 1 followers.
