### ISSUE TITLE
Chat error msg "Error: environment effect incomplete: 228"

### ISSUE THREAD

**Issue by Nillx** [teelolws/TLDRMissions#16]
Got this error "Error: environment effect incomplete: 228" on the mission Vmbral Regiment - Necrolord. Also it kept calculating the outcome until i reloaded UI

![Screenshot 2022-04-12 000551](https://user-images.githubusercontent.com/34476875/162833431-8a64b71f-3c04-4773-a3d9-a2e9417b381d.jpg)

VP predicted a win with this troops
![Screenshot 2022-04-12 001102](https://user-images.githubusercontent.com/34476875/162833892-cf0dedc5-ffe5-4367-8ee2-bfe9c158cc0a.jpg)

Also are reports like this useful?

**Comment by teelolws** [comment]
Its not Umbral Regiment causing that error. It'll be one of your Maw missions. Something about the Tremulacrum. I haven't seen that mission yet so haven't been able to test it.

If you haven't sent that mission out yet, can you test this?
[simulation.zip](https://github.com/teelolws/TLDRMissions/files/8467838/simulation.zip)

**Comment by Nillx** [comment]
Where do i put this? And could it be this mission?
![Screenshot 2022-04-12 002916](https://user-images.githubusercontent.com/34476875/162836565-67181c0c-0ae2-44ad-baeb-78ed639d486f.jpg)

**Comment by teelolws** [comment]
Yeah its that one. 6200 damage. I'll have to fix that, I've got it at only 1,000 damage.

**Comment by Nillx** [comment]
Alright and i replaced the file you sent but i already sent most of my followers on different missions

**Comment by teelolws** [comment]
If you still have at least one follower back, just see if any errors or anything popup. I don't need it to actually find a way to complete that mission. Those ones basically require all level 60 followers.

**Comment by Nillx** [comment]
Im unable to figure out how to make the addon simulate that specific mission. Selecting all rewards + "Then any remaining" doesnt attempt to simulate that mission. (Noticed that the addon does not attempt to simulate missions that reward crates with different mats and missions that reward epic items as rewards)

**Comment by Nillx** [comment]
I guess it does that because i cannot win that mission with the followers i have atm. There are no errors after the sim is complete.

**Comment by teelolws** [comment]
Try making it sort by hardest mission first.

**Comment by Nillx** [comment]
Tried that. Addon did the simulation and gave me a prediction for 3 missions. That Maw one got skipped. This are my active missions:
![5](https://user-images.githubusercontent.com/34476875/162839018-3d8735d9-302e-496e-b5a8-11d2331c5746.jpg)

And  this are the missions that were simulated:
![1](https://user-images.githubusercontent.com/34476875/162839104-749ea97e-9e7c-4c0d-8c0d-cce24c96c9f1.jpg)
![2](https://user-images.githubusercontent.com/34476875/162839107-a295ad95-c76d-458e-a7de-0faa47aa6c2d.jpg)
![3](https://user-images.githubusercontent.com/34476875/162839108-85738691-9a53-4351-8d78-b87f6a0f72cf.jpg)
![4](https://user-images.githubusercontent.com/34476875/162839110-4455cfa2-87ec-4877-9fc7-0687829636e2.jpg)

**Comment by teelolws** [comment]
Okay it just means it couldn't find a way to win that Maw mission. As long as no errors appeared, my changes should be fine. Thanks for testing, and I'll upload the new version later today when I'm finished working on other things!

**Comment by Nillx** [comment]
No worries, im happy to help! Also can you add a checkbox option for the missions that reward crates with different mats and missions that reward epic items?

**Comment by teelolws** [comment]
Thats on my list: https://github.com/teelolws/TLDRMissions/issues/4

Its not simple. Theres a lot of different caches and crafting materials, different for each covenant, and I have to make a list of all the Item IDs for them.

**Comment by Nillx** [comment]
Error: environment effect incomplete: 228 seems to be back again today when i did a scan for different errors.

**Comment by teelolws** [comment]
Whoops. Should be fixed in 9.2-014, which is going up soon.
