### ISSUE TITLE
[BUG] A mission failed!

### ISSUE THREAD

**Issue by truetraffic** [teelolws/TLDRMissions#161]
[Upload your Saved Variables here]
You can find your Saved Variables in your WoW folder, under WTF \ Account \ YOUR ACCOUNT \ YOUR REALM \ YOUR CHARACTER \ SavedVariables \ TLDRMissions.lua

Github won't allow you to upload a .lua file directly, but you can either .zip it up or just copy/paste the entire contents of the file here.
[TLDRMissions.zip](https://github.com/teelolws/TLDRMissions/files/8647011/TLDRMissions.zip)

**Comment by teelolws** [comment]
Thanks, having ongoing issues with mission 2188 (Possessed Scavengers) and have filed your log under https://github.com/teelolws/TLDRMissions/issues/88 for investigation.
