### ISSUE TITLE
Russian locale

### ISSUE THREAD

**Issue by SappFire2008** [teelolws/TLDRMissions#162]
Went a bit ahead and translated enus.lua to russian ruru.lua
Thanks for great addon

Tried to make it as short as possible to not break current design, but currently have an issue with "Skip" button size, as russian shortest equvalent is "Пропуск" doesn't fit it.
Also, if possible, allow to rename second tab where all settings goes. If you'll implement that, russian one will be "Настройки"
Screenshots how it currently looks
![Simulating](https://user-images.githubusercontent.com/105151052/167306189-c176908e-47ff-46f6-b2a4-63ed826a5e7a.png)
![tab1](https://user-images.githubusercontent.com/105151052/167306195-e95e67ff-1d85-4d84-b322-ad874b47e6fc.png)
![tab2](https://user-images.githubusercontent.com/105151052/167306197-b64ee6e3-386d-4fd2-af79-88d3ef43bafc.png)
![tab3](https://user-images.githubusercontent.com/105151052/167306198-6af788d9-f1e4-4852-84fd-e523b75a5474.png)

Zip file with translated file

[ruRU.zip](https://github.com/teelolws/TLDRMissions/files/8647408/ruRU.zip)

**Comment by teelolws** [comment]
Thanks. If you need to make changes, make a pull request for this file: https://github.com/teelolws/TLDRMissions/blob/main/Translations/ruRU.lua

I'll widen the Skip button a bit.

As for the tab button width, that width gets set by Blizzard based on the text inside. I don't know how to override it to make it wider.
