### ISSUE TITLE
[Suggestion] change order of priority

### ISSUE THREAD

**Issue by Majorcast** [teelolws/TLDRMissions#165]
be able to shift priority of your type of missions, without having to reset anything else.

ex.
If gold is 2, Anima is 3, crafting resources is 4

Be able to shift gold and anima with eachother, while keeping crafting resources at 4. without having to unclick crafting resource.

**Comment by teelolws** [comment]
I wanted to do something nicer like that but WoW doesn't have any UI elements to make that simple. In a Windows program I would have used a drag-n-drop List Box, but no such thing exists in WoW. Its pretty limited in what I can use in the UI, unfortunately. I'd have to make a ListBox from scratch and thats a bit outside of my area of expertise.
