### ISSUE TITLE
[BUG] Lua error

### ISSUE THREAD

**Issue by TGJH** [teelolws/TLDRMissions#173]
LUA text below, the only other thing I can add is that I ran out of anima during the Calculate phase. Not sure if that is relevant or not.

Message: Interface\AddOns\TLDRMissions\guihandlers.lua:261: attempt to perform arithmetic on field 'offerEndTime' (a nil value)
Time: Tue May 10 18:06:23 2022
Count: 1
Stack: Interface\AddOns\TLDRMissions\guihandlers.lua:261: attempt to perform arithmetic on field 'offerEndTime' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "@Interface\AddOns\TLDRMissions\guihandlers.lua"]:261: in function <Interface\AddOns\TLDRMissions\guihandlers.lua:211>
[string "@Interface\AddOns\TLDRMissions\guihandlers.lua"]:679: in function <Interface\AddOns\TLDRMissions\guihandlers.lua:668>
[string "@Interface\AddOns\TLDRMissions\guihandlers.lua"]:566: in function `garrisonMissionStartedHandler'
[string "@Interface\AddOns\TLDRMissions\events.lua"]:54: in function <Interface\AddOns\TLDRMissions\events.lua:39>

Locals: errMsg = "Interface\AddOns\TLDRMissions\guihandlers.lua:261: attempt to perform arithmetic on field 'offerEndTime' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by teelolws** [comment]
Apparently you have a mission that never expires. I didn't know that was possible.

**Comment by teelolws** [comment]
Replace the guihandlers.lua file in the addon directory with this. I'll include it properly in the next patch tomorrow.
[guihandlers.zip](https://github.com/teelolws/TLDRMissions/files/8658739/guihandlers.zip)

**Comment by TGJH** [comment]
That is some seriously fast investigation.

No wonder your addon is becoming so popular. Awesome :-)

Cheers

Trev
