### ISSUE TITLE
[BUG] A mission failed!

### ISSUE THREAD

**Issue by cochesey** [teelolws/TLDRMissions#174]
[Upload your Saved Variables here]
You can find your Saved Variables in your WoW folder, under WTF \ Account \ YOUR ACCOUNT \ YOUR REALM \ YOUR CHARACTER \ SavedVariables \ TLDRMissions.lua

Github won't allow you to upload a .lua file directly, but you can either .zip it up or just copy/paste the entire contents of the file here.

TLDRMissionsOptions = {
	["lowestOrHighest"] = "lowest",
	["followerXPSpecialTreatment"] = true,
	["moreOrLessTroops"] = "more",
	["craftingCacheTypes"] = {
		[131474] = {
			true, -- [1]
			true, -- [2]
			true, -- [3]
		},
		[2575] = {
			true, -- [1]
			true, -- [2]
			true, -- [3]
		},
		[8613] = {
			true, -- [1]
			true, -- [2]
			true, -- [3]
		},
		["zereth"] = {
			true, -- [1]
			true, -- [2]
			true, -- [3]
		},
		[3908] = {
			true, -- [1]
			true, -- [2]
			true, -- [3]
		},
		[7411] = {
			true, -- [1]
			true, -- [2]
			true, -- [3]
		},
		[2550] = {
			true, -- [1]
			true, -- [2]
			true, -- [3]
		},
		[2366] = {
			true, -- [1]
			true, -- [2]
			true, -- [3]
		},
	},
	["reputations"] = {
		[1806] = true,
		[1804] = true,
		[1805] = true,
		[1807] = true,
	},
	["workPerFrame"] = 200,
	["fewestOrMost"] = "fewest",
	["selectedRewards"] = {
		"followerxp", -- [1]
		"followerxp-items", -- [2]
		"gold", -- [3]
		"augment-runes", -- [4]
		"anima", -- [5]
		"reputation", -- [6]
		"crafting-cache", -- [7]
		"runecarver", -- [8]
	},
	["excludedRewards"] = {
		"campaign", -- [1]
	},
	["hardestOrEasiest"] = "easy",
	["runecarver"] = {
		[1767] = false,
		[1828] = true,
		[2009] = true,
		[1906] = true,
	},
}
TLDRMissionsLogging = {
	[2238] = {
		["missionID"] = 2238,
		["followers"] = {
			{
				["maxHP"] = 1530,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 2,
						["spellID"] = 79,
					}, -- [1]
				},
				["predictedFinalHP"] = -102,
				["name"] = "Disciple Kosmas",
				["followerID"] = "0x0000000030ADDB71",
				["baseAttack"] = 204,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 1530,
				["boardIndex"] = 2,
			}, -- [1]
			{
				["maxHP"] = 750,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 50,
					}, -- [1]
				},
				["predictedFinalHP"] = 53,
				["name"] = "Kyrian Halberdier",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 200,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 750,
				["boardIndex"] = 3,
			}, -- [2]
			{
				["maxHP"] = 750,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 50,
					}, -- [1]
				},
				["predictedFinalHP"] = 162,
				["name"] = "Kyrian Halberdier",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 200,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 750,
				["boardIndex"] = 4,
			}, -- [3]
			{
				["maxHP"] = 750,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 50,
					}, -- [1]
				},
				["predictedFinalHP"] = -18,
				["name"] = "Kyrian Halberdier",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 200,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 750,
				["boardIndex"] = 0,
			}, -- [4]
			{
				["maxHP"] = 750,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 50,
					}, -- [1]
				},
				["predictedFinalHP"] = 678,
				["name"] = "Kyrian Halberdier",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 200,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 750,
				["boardIndex"] = 1,
			}, -- [5]
		},
		["addonVersion"] = "9.2-047",
		["enemies"] = {
			{
				["maxHP"] = 2925,
				["spells"] = {
					{
						["duration"] = 3,
						["cooldown"] = 4,
						["spellID"] = 174,
					}, -- [1]
				},
				["name"] = "Privileged Contributor",
				["boardIndex"] = 10,
				["baseAttack"] = 181,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 2925,
				["followerID"] = -1,
			}, -- [1]
			{
				["maxHP"] = 1355,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 175,
					}, -- [1]
				},
				["name"] = "Party Animal",
				["boardIndex"] = 6,
				["baseAttack"] = 139,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1355,
				["followerID"] = -2,
			}, -- [2]
			{
				["maxHP"] = 1355,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 175,
					}, -- [1]
				},
				["name"] = "Party Animal",
				["boardIndex"] = 7,
				["baseAttack"] = 139,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1355,
				["followerID"] = -3,
			}, -- [3]
			{
				["maxHP"] = 1355,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 175,
					}, -- [1]
				},
				["name"] = "Party Animal",
				["boardIndex"] = 5,
				["baseAttack"] = 139,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1355,
				["followerID"] = -4,
			}, -- [4]
			{
				["maxHP"] = 1355,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 175,
					}, -- [1]
				},
				["name"] = "Party Animal",
				["boardIndex"] = 8,
				["baseAttack"] = 139,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1355,
				["followerID"] = -5,
			}, -- [5]
		},
	},
	[2235] = {
		["missionID"] = 2235,
		["followers"] = {
			{
				["maxHP"] = 1125,
				["spells"] = {
					{
						["duration"] = 2,
						["cooldown"] = 3,
						["spellID"] = 315,
					}, -- [1]
				},
				["predictedFinalHP"] = 858,
				["name"] = "Hermestes",
				["followerID"] = "0x000000003FC2DB86",
				["baseAttack"] = 225,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 1125,
				["boardIndex"] = 2,
			}, -- [1]
			{
				["maxHP"] = 2000,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 83,
					}, -- [1]
					{
						["duration"] = 0,
						["cooldown"] = 0,
						["spellID"] = 82,
					}, -- [2]
				},
				["predictedFinalHP"] = 1270,
				["name"] = "Kleia",
				["followerID"] = "0x00000000303AB108",
				["baseAttack"] = 200,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1455,
				["boardIndex"] = 3,
			}, -- [2]
			{
				["maxHP"] = 1000,
				["spells"] = {
					{
						["duration"] = 3,
						["cooldown"] = 5,
						["spellID"] = 77,
					}, -- [1]
				},
				["predictedFinalHP"] = 1000,
				["name"] = "Sika",
				["followerID"] = "0x00000000302C88A5",
				["baseAttack"] = 200,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 1000,
				["boardIndex"] = 4,
			}, -- [3]
			{
				["maxHP"] = 1500,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 2,
						["spellID"] = 87,
					}, -- [1]
					{
						["duration"] = 3,
						["cooldown"] = 3,
						["spellID"] = 88,
					}, -- [2]
				},
				["predictedFinalHP"] = 1145,
				["name"] = "Pelagos",
				["followerID"] = "0x00000000302C8778",
				["baseAttack"] = 200,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 1145,
				["boardIndex"] = 0,
			}, -- [4]
			{
				["maxHP"] = 1000,
				["spells"] = {
					{
						["duration"] = 2,
						["cooldown"] = 3,
						["spellID"] = 85,
					}, -- [1]
					{
						["duration"] = 2,
						["cooldown"] = 4,
						["spellID"] = 84,
					}, -- [2]
				},
				["predictedFinalHP"] = 775,
				["name"] = "Mikanikos",
				["followerID"] = "0x0000000030477202",
				["baseAttack"] = 250,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 775,
				["boardIndex"] = 1,
			}, -- [5]
		},
		["addonVersion"] = "9.2-047",
		["enemies"] = {
			{
				["maxHP"] = 2000,
				["spells"] = {
					{
						["duration"] = 3,
						["cooldown"] = 5,
						["spellID"] = 169,
					}, -- [1]
				},
				["name"] = "Invading Riftkeeper",
				["boardIndex"] = 6,
				["baseAttack"] = 85,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 2000,
				["followerID"] = -1,
			}, -- [1]
			{
				["maxHP"] = 2000,
				["spells"] = {
					{
						["duration"] = 3,
						["cooldown"] = 5,
						["spellID"] = 169,
					}, -- [1]
				},
				["name"] = "Invading Riftkeeper",
				["boardIndex"] = 7,
				["baseAttack"] = 85,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 2000,
				["followerID"] = -2,
			}, -- [2]
		},
	},
	[2221] = {
		["combatLog"] = {
			",", -- [1]
			"Start of round 1", -- [2]
			",", -- [3]
			"Teliah[0] shot Steelspine Wallbreaker[12][1140HP] for 200 damage.", -- [4]
			"Teliah[0] cast Shining Spear at Steelspine Wallbreaker[12][780HP] for 360  damage.", -- [5]
			"Teliah[0] cast Shining Spear on Kyrian Halberdier[2][750HP] for 40 healing.", -- [6]
			"Kyrian Halberdier[1] meleed Steelspine Vanguard[6][3340HP] for 200 damage.", -- [7]
			"Kyrian Halberdier[1] cast Halberd Strike at Steelspine Wallbreaker[9][1100HP] for 240  damage.", -- [8]
			"Kyrian Halberdier[2] meleed Steelspine Vanguard[6][3140HP] for 200 damage.", -- [9]
			"Kyrian Halberdier[2] cast Halberd Strike at Steelspine Wallbreaker[12][540HP] for 240  damage.", -- [10]
			"Kyrian Halberdier[3] meleed Steelspine Vanguard[6][2940HP] for 200 damage.", -- [11]
			"Kyrian Halberdier[3] cast Halberd Strike at Steelspine Wallbreaker[9][860HP] for 240  damage.", -- [12]
			"Kyrian Halberdier[4] meleed Steelspine Vanguard[7][3340HP] for 200 damage.", -- [13]
			"Kyrian Halberdier[4] cast Halberd Strike at Steelspine Wallbreaker[9][620HP] for 240  damage.", -- [14]
			"Steelspine Vanguard[6] meleed Kyrian Halberdier[2][653HP] for 97 damage.", -- [15]
			"Steelspine Vanguard[7] meleed Kyrian Halberdier[3][653HP] for 97 damage.", -- [16]
			"Steelspine Wallbreaker[9] shot Kyrian Halberdier[4][653HP] for 97 damage.", -- [17]
			"Steelspine Wallbreaker[9] applied Ritual Fervor to Steelspine Vanguard[7][3340HP].", -- [18]
			"Steelspine Wallbreaker[10] shot Kyrian Halberdier[1][653HP] for 97 damage.", -- [19]
			"Steelspine Wallbreaker[10] applied Ritual Fervor to Steelspine Vanguard[7][3340HP].", -- [20]
			"Steelspine Wallbreaker[11] shot Teliah[0][1153HP] for 97 damage.", -- [21]
			"Steelspine Wallbreaker[11] applied Ritual Fervor to Steelspine Vanguard[7][3340HP].", -- [22]
			"Steelspine Wallbreaker[12] shot Kyrian Halberdier[2][556HP] for 97 damage.", -- [23]
			"Steelspine Wallbreaker[12] applied Ritual Fervor to Steelspine Vanguard[7][3340HP].", -- [24]
			",", -- [25]
			"Start of round 2", -- [26]
			",", -- [27]
			"Teliah[0] shot Steelspine Wallbreaker[12][340HP] for 200 damage.", -- [28]
			"Kyrian Halberdier[1] meleed Steelspine Vanguard[6][2740HP] for 200 damage.", -- [29]
			"Kyrian Halberdier[3] meleed Steelspine Vanguard[6][2540HP] for 200 damage.", -- [30]
			"Kyrian Halberdier[4] meleed Steelspine Vanguard[7][3140HP] for 200 damage.", -- [31]
			"Kyrian Halberdier[2] meleed Steelspine Vanguard[6][2340HP] for 200 damage.", -- [32]
			"Steelspine Vanguard[7] meleed Kyrian Halberdier[3][362HP] for 291 damage.", -- [33]
			"Steelspine Vanguard[6] meleed Kyrian Halberdier[2][459HP] for 97 damage.", -- [34]
			"Steelspine Wallbreaker[10] removed Ritual Fervor from Steelspine Vanguard[7][3140HP].", -- [35]
			"Steelspine Wallbreaker[10] shot Kyrian Halberdier[1][556HP] for 97 damage.", -- [36]
			"Steelspine Wallbreaker[11] removed Ritual Fervor from Steelspine Vanguard[7][3140HP].", -- [37]
			"Steelspine Wallbreaker[11] shot Teliah[0][1056HP] for 97 damage.", -- [38]
			"Steelspine Wallbreaker[9] removed Ritual Fervor from Steelspine Vanguard[7][3140HP].", -- [39]
			"Steelspine Wallbreaker[9] shot Kyrian Halberdier[4][556HP] for 97 damage.", -- [40]
			"Steelspine Wallbreaker[12] removed Ritual Fervor from Steelspine Vanguard[7][3140HP].", -- [41]
			"Steelspine Wallbreaker[12] shot Kyrian Halberdier[2][362HP] for 97 damage.", -- [42]
			",", -- [43]
			"Start of round 3", -- [44]
			",", -- [45]
			"Teliah[0] shot Steelspine Wallbreaker[12][140HP] for 200 damage.", -- [46]
			"Kyrian Halberdier[1] meleed Steelspine Vanguard[6][2140HP] for 200 damage.", -- [47]
			"Kyrian Halberdier[4] meleed Steelspine Vanguard[7][2940HP] for 200 damage.", -- [48]
			"Kyrian Halberdier[2] meleed Steelspine Vanguard[6][1940HP] for 200 damage.", -- [49]
			"Kyrian Halberdier[3] meleed Steelspine Vanguard[6][1740HP] for 200 damage.", -- [50]
			"Steelspine Vanguard[7] meleed Kyrian Halberdier[3][265HP] for 97 damage.", -- [51]
			"Steelspine Vanguard[6] meleed Kyrian Halberdier[2][265HP] for 97 damage.", -- [52]
			"Steelspine Wallbreaker[10] shot Kyrian Halberdier[1][459HP] for 97 damage.", -- [53]
			"Steelspine Wallbreaker[11] shot Teliah[0][959HP] for 97 damage.", -- [54]
			"Steelspine Wallbreaker[9] shot Kyrian Halberdier[4][459HP] for 97 damage.", -- [55]
			"Steelspine Wallbreaker[12] shot Kyrian Halberdier[2][168HP] for 97 damage.", -- [56]
			",", -- [57]
			"Start of round 4", -- [58]
			",", -- [59]
			"Teliah[0] shot Steelspine Wallbreaker[12][0HP] for 200 damage.", -- [60]
			"Teliah[0] killed Steelspine Wallbreaker[12][0HP].", -- [61]
			"Teliah[0] cast Shining Spear at Steelspine Wallbreaker[9][260HP] for 360  damage.", -- [62]
			"Teliah[0] cast Shining Spear on Kyrian Halberdier[2][208HP] for 40 healing.", -- [63]
			"Kyrian Halberdier[1] meleed Steelspine Vanguard[6][1540HP] for 200 damage.", -- [64]
			"Kyrian Halberdier[4] meleed Steelspine Vanguard[7][2740HP] for 200 damage.", -- [65]
			"Kyrian Halberdier[3] meleed Steelspine Vanguard[6][1340HP] for 200 damage.", -- [66]
			"Kyrian Halberdier[2] meleed Steelspine Vanguard[6][1140HP] for 200 damage.", -- [67]
			"Steelspine Vanguard[7] meleed Kyrian Halberdier[3][168HP] for 97 damage.", -- [68]
			"Steelspine Vanguard[6] meleed Kyrian Halberdier[2][111HP] for 97 damage.", -- [69]
			"Steelspine Wallbreaker[10] shot Kyrian Halberdier[1][362HP] for 97 damage.", -- [70]
			"Steelspine Wallbreaker[10] applied Ritual Fervor to Steelspine Vanguard[7][2740HP].", -- [71]
			"Steelspine Wallbreaker[11] shot Teliah[0][862HP] for 97 damage.", -- [72]
			"Steelspine Wallbreaker[11] applied Ritual Fervor to Steelspine Vanguard[7][2740HP].", -- [73]
			"Steelspine Wallbreaker[9] shot Kyrian Halberdier[4][362HP] for 97 damage.", -- [74]
			"Steelspine Wallbreaker[9] applied Ritual Fervor to Steelspine Vanguard[7][2740HP].", -- [75]
			",", -- [76]
			"Start of round 5", -- [77]
			",", -- [78]
			"Teliah[0] shot Steelspine Wallbreaker[9][60HP] for 200 damage.", -- [79]
			"Kyrian Halberdier[1] meleed Steelspine Vanguard[6][940HP] for 200 damage.", -- [80]
			"Kyrian Halberdier[1] cast Halberd Strike at Steelspine Wallbreaker[9][0HP] for 240  damage.", -- [81]
			"Kyrian Halberdier[1] killed Steelspine Wallbreaker[9][0HP].", -- [82]
			"Kyrian Halberdier[4] meleed Steelspine Vanguard[7][2540HP] for 200 damage.", -- [83]
			"Kyrian Halberdier[4] cast Halberd Strike at Steelspine Wallbreaker[10][1100HP] for 240  damage.", -- [84]
			"Kyrian Halberdier[3] meleed Steelspine Vanguard[6][740HP] for 200 damage.", -- [85]
			"Kyrian Halberdier[3] cast Halberd Strike at Steelspine Wallbreaker[10][860HP] for 240  damage.", -- [86]
			"Kyrian Halberdier[2] meleed Steelspine Vanguard[6][540HP] for 200 damage.", -- [87]
			"Kyrian Halberdier[2] cast Halberd Strike at Steelspine Wallbreaker[11][1100HP] for 240  damage.", -- [88]
			"Steelspine Vanguard[7] meleed Kyrian Halberdier[3][0HP] for 242 damage.", -- [89]
			"Steelspine Vanguard[7] killed Kyrian Halberdier[3][0HP].", -- [90]
			"Steelspine Wallbreaker[10] removed Ritual Fervor from Steelspine Vanguard[7][2540HP].", -- [91]
			"Steelspine Wallbreaker[10] shot Kyrian Halberdier[1][265HP] for 97 damage.", -- [92]
			"Steelspine Wallbreaker[11] removed Ritual Fervor from Steelspine Vanguard[7][2540HP].", -- [93]
			"Steelspine Wallbreaker[11] shot Teliah[0][765HP] for 97 damage.", -- [94]
			"Steelspine Vanguard[6] meleed Kyrian Halberdier[2][14HP] for 97 damage.", -- [95]
			"Steelspine Wallbreaker[9] removed Ritual Fervor from Steelspine Vanguard[7][2540HP].", -- [96]
			",", -- [97]
			"Start of round 6", -- [98]
			",", -- [99]
			"Teliah[0] shot Steelspine Wallbreaker[11][900HP] for 200 damage.", -- [100]
			"Kyrian Halberdier[4] meleed Steelspine Vanguard[7][2340HP] for 200 damage.", -- [101]
			"Kyrian Halberdier[1] meleed Steelspine Vanguard[6][340HP] for 200 damage.", -- [102]
			"Kyrian Halberdier[2] meleed Steelspine Vanguard[6][140HP] for 200 damage.", -- [103]
			"Steelspine Vanguard[7] meleed Kyrian Halberdier[4][265HP] for 97 damage.", -- [104]
			"Steelspine Wallbreaker[11] shot Teliah[0][668HP] for 97 damage.", -- [105]
			"Steelspine Wallbreaker[10] shot Kyrian Halberdier[1][168HP] for 97 damage.", -- [106]
			"Steelspine Vanguard[6] meleed Kyrian Halberdier[2][0HP] for 97 damage.", -- [107]
			"Steelspine Vanguard[6] killed Kyrian Halberdier[2][0HP].", -- [108]
			",", -- [109]
			"Start of round 7", -- [110]
			",", -- [111]
			"Teliah[0] shot Steelspine Wallbreaker[11][700HP] for 200 damage.", -- [112]
			"Teliah[0] cast Shining Spear at Steelspine Wallbreaker[11][340HP] for 360  damage.", -- [113]
			"Teliah[0] cast Shining Spear on Kyrian Halberdier[1][208HP] for 40 healing.", -- [114]
			"Kyrian Halberdier[4] meleed Steelspine Vanguard[7][2140HP] for 200 damage.", -- [115]
			"Kyrian Halberdier[1] meleed Steelspine Vanguard[6][0HP] for 200 damage.", -- [116]
			"Kyrian Halberdier[1] killed Steelspine Vanguard[6][0HP].", -- [117]
			"Steelspine Vanguard[7] meleed Kyrian Halberdier[4][168HP] for 97 damage.", -- [118]
			"Steelspine Wallbreaker[11] shot Teliah[0][571HP] for 97 damage.", -- [119]
			"Steelspine Wallbreaker[11] applied Ritual Fervor to Steelspine Wallbreaker[10][860HP].", -- [120]
			"Steelspine Wallbreaker[10] shot Kyrian Halberdier[1][63HP] for 145 damage.", -- [121]
			"Steelspine Wallbreaker[10] applied Ritual Fervor to Steelspine Wallbreaker[10][860HP].", -- [122]
			",", -- [123]
			"Start of round 8", -- [124]
			",", -- [125]
			"Teliah[0] shot Steelspine Wallbreaker[11][140HP] for 200 damage.", -- [126]
			"Kyrian Halberdier[4] meleed Steelspine Vanguard[7][1940HP] for 200 damage.", -- [127]
			"Kyrian Halberdier[1] meleed Steelspine Vanguard[7][1740HP] for 200 damage.", -- [128]
			"Steelspine Vanguard[7] meleed Kyrian Halberdier[4][71HP] for 97 damage.", -- [129]
			"Steelspine Wallbreaker[10] removed Ritual Fervor from Steelspine Wallbreaker[10][860HP].", -- [130]
			"Steelspine Wallbreaker[10] shot Kyrian Halberdier[1][0HP] for 145 damage.", -- [131]
			"Steelspine Wallbreaker[10] killed Kyrian Halberdier[1][0HP].", -- [132]
			"Steelspine Wallbreaker[11] removed Ritual Fervor from Steelspine Wallbreaker[10][860HP].", -- [133]
			"Steelspine Wallbreaker[11] shot Teliah[0][474HP] for 97 damage.", -- [134]
			",", -- [135]
			"Start of round 9", -- [136]
			",", -- [137]
			"Teliah[0] shot Steelspine Wallbreaker[11][0HP] for 200 damage.", -- [138]
			"Teliah[0] killed Steelspine Wallbreaker[11][0HP].", -- [139]
			"Kyrian Halberdier[4] meleed Steelspine Vanguard[7][1540HP] for 200 damage.", -- [140]
			"Kyrian Halberdier[4] cast Halberd Strike at Steelspine Wallbreaker[10][620HP] for 240  damage.", -- [141]
			"Steelspine Vanguard[7] meleed Kyrian Halberdier[4][0HP] for 97 damage.", -- [142]
			"Steelspine Vanguard[7] killed Kyrian Halberdier[4][0HP].", -- [143]
			"Steelspine Wallbreaker[10] shot Teliah[0][377HP] for 97 damage.", -- [144]
			",", -- [145]
			"Start of round 10", -- [146]
			",", -- [147]
			"Teliah[0] shot Steelspine Wallbreaker[10][420HP] for 200 damage.", -- [148]
			"Teliah[0] cast Shining Spear at Steelspine Wallbreaker[10][60HP] for 360  damage.", -- [149]
			"Teliah[0] cast Shining Spear on Teliah[0][417HP] for 40 healing.", -- [150]
			"Steelspine Vanguard[7] meleed Teliah[0][320HP] for 97 damage.", -- [151]
			"Steelspine Wallbreaker[10] shot Teliah[0][223HP] for 97 damage.", -- [152]
			"Steelspine Wallbreaker[10] applied Ritual Fervor to Steelspine Wallbreaker[10][60HP].", -- [153]
			",", -- [154]
			"Start of round 11", -- [155]
			",", -- [156]
			"Teliah[0] shot Steelspine Wallbreaker[10][0HP] for 200 damage.", -- [157]
			"Teliah[0] killed Steelspine Wallbreaker[10][0HP].", -- [158]
			"Steelspine Vanguard[7] meleed Teliah[0][126HP] for 97 damage.", -- [159]
			",", -- [160]
			"Start of round 12", -- [161]
			",", -- [162]
			"Teliah[0] shot Steelspine Vanguard[7][1340HP] for 200 damage.", -- [163]
			"Steelspine Vanguard[7] meleed Teliah[0][29HP] for 97 damage.", -- [164]
			",", -- [165]
			"Start of round 13", -- [166]
			",", -- [167]
			"Teliah[0] shot Steelspine Vanguard[7][1140HP] for 200 damage.", -- [168]
			"Teliah[0] cast Shining Spear at Steelspine Vanguard[7][780HP] for 360  damage.", -- [169]
			"Teliah[0] cast Shining Spear on Teliah[0][69HP] for 40 healing.", -- [170]
			"Steelspine Vanguard[7] meleed Teliah[0][0HP] for 97 damage.", -- [171]
			"Steelspine Vanguard[7] killed Teliah[0][0HP].", -- [172]
		},
		["addonVersion"] = "9.2-047",
		["followers"] = {
			{
				["maxHP"] = 750,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 50,
					}, -- [1]
				},
				["predictedFinalHP"] = -83,
				["name"] = "Kyrian Halberdier",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 200,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 750,
				["boardIndex"] = 2,
			}, -- [1]
			{
				["maxHP"] = 750,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 50,
					}, -- [1]
				},
				["predictedFinalHP"] = -74,
				["name"] = "Kyrian Halberdier",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 200,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 750,
				["boardIndex"] = 3,
			}, -- [2]
			{
				["maxHP"] = 750,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 50,
					}, -- [1]
				},
				["predictedFinalHP"] = -26,
				["name"] = "Kyrian Halberdier",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 200,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 750,
				["boardIndex"] = 4,
			}, -- [3]
			{
				["maxHP"] = 1250,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 2,
						["spellID"] = 24,
					}, -- [1]
				},
				["predictedFinalHP"] = 69,
				["name"] = "Teliah",
				["followerID"] = "0x0000000030DA4FCE",
				["baseAttack"] = 200,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 1250,
				["boardIndex"] = 0,
			}, -- [4]
			{
				["maxHP"] = 750,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 50,
					}, -- [1]
				},
				["predictedFinalHP"] = -83,
				["name"] = "Kyrian Halberdier",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 200,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 750,
				["boardIndex"] = 1,
			}, -- [5]
		},
		["missionID"] = 2221,
		["enemies"] = {
			{
				["maxHP"] = 3540,
				["spells"] = {
					{
						["duration"] = 2,
						["cooldown"] = 4,
						["spellID"] = 208,
					}, -- [1]
				},
				["name"] = "Steelspine Vanguard",
				["boardIndex"] = 6,
				["baseAttack"] = 97,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 3540,
				["followerID"] = -1,
			}, -- [1]
			{
				["maxHP"] = 3540,
				["spells"] = {
					{
						["duration"] = 2,
						["cooldown"] = 4,
						["spellID"] = 208,
					}, -- [1]
				},
				["name"] = "Steelspine Vanguard",
				["boardIndex"] = 7,
				["baseAttack"] = 97,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 3540,
				["followerID"] = -2,
			}, -- [2]
			{
				["maxHP"] = 1340,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 209,
					}, -- [1]
				},
				["name"] = "Steelspine Wallbreaker",
				["boardIndex"] = 9,
				["baseAttack"] = 97,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 1340,
				["followerID"] = -3,
			}, -- [3]
			{
				["maxHP"] = 1340,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 209,
					}, -- [1]
				},
				["name"] = "Steelspine Wallbreaker",
				["boardIndex"] = 10,
				["baseAttack"] = 97,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 1340,
				["followerID"] = -4,
			}, -- [4]
			{
				["maxHP"] = 1340,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 209,
					}, -- [1]
				},
				["name"] = "Steelspine Wallbreaker",
				["boardIndex"] = 11,
				["baseAttack"] = 97,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 1340,
				["followerID"] = -5,
			}, -- [5]
			{
				["maxHP"] = 1340,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 209,
					}, -- [1]
				},
				["name"] = "Steelspine Wallbreaker",
				["boardIndex"] = 12,
				["baseAttack"] = 97,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 1340,
				["followerID"] = -6,
			}, -- [6]
		},
	},
}

**Comment by teelolws** [comment]
Thanks. Filing this with ongoing issues with the Spines of Steel and Sorrow (2221) mission being investigated here: https://github.com/teelolws/TLDRMissions/issues/86
