### ISSUE TITLE
Translation de_DE

### ISSUE THREAD

**Issue by marco-kretz** [teelolws/TLDRMissions#181]
Hey,

really appreciate your work and would like to support you with the German translations :)

**Comment by teelolws** [comment]
Great! 

First, fork this repository. 

Then, take this file: https://github.com/teelolws/TLDRMissions/blob/main/Translations/deDE.lua

Fill in your translations, then make a pull request with your corrections.

**Comment by teelolws** [comment]
Because Curseforge isn't accepting my patch that fixes it:
![image](https://user-images.githubusercontent.com/49792789/168385235-be550bc3-4e0e-4fdd-814b-0449ed651ae1.png)
