### ISSUE TITLE
[Ger translation] Umlauts are not shown

### ISSUE THREAD

**Issue by christin-schlimbach** [teelolws/TLDRMissions#188]
In the German translation, the umlauts are not displayed. Instead, a small square is shown.
![WhatsApp Image 2022-05-13 at 10 46 13](https://user-images.githubusercontent.com/6771962/168249578-38d11d8e-92f5-4285-9e3f-88d1333c8300.jpeg)

**Comment by teelolws** [comment]
[TLDRMissions.zip](https://github.com/teelolws/TLDRMissions/files/8685718/TLDRMissions.zip)

I forgot to change the encoding of deDE.lua from ANSI to UNICODE. Quick fix being uploaded now.

**Comment by christin-schlimbach** [comment]
Ty for your quick support :)

**Comment by teelolws** [comment]
Can you confirm its fixed in patch 055?
