### ISSUE TITLE
[BUG] Timeout on "random_ally" missions

### ISSUE THREAD

**Issue by kittykiller** [teelolws/TLDRMissions#19]
1x TLDRMissions\simulation.lua:875: script ran too long
[string "@TLDRMissions\simulation.lua"]:875: in function <TLDRMissions\simulation.lua:841>
[string "@TLDRMissions\simulation.lua"]:1088: in function <TLDRMissions\simulation.lua:1015>
[string "@TLDRMissions\simulation.lua"]:1422: in function <TLDRMissions\simulation.lua:1390>
[string "@TLDRMissions\simulation.lua"]:1433: in function <TLDRMissions\simulation.lua:1390>
[string "@TLDRMissions\simulation.lua"]:1433: in function <TLDRMissions\simulation.lua:1390>
[string "@TLDRMissions\simulation.lua"]:1433: in function <TLDRMissions\simulation.lua:1390>
[string "@TLDRMissions\simulation.lua"]:1433: in function <TLDRMissions\simulation.lua:1390>
[string "@TLDRMissions\simulation.lua"]:1433: in function <TLDRMissions\simulation.lua:1390>
[string "@TLDRMissions\simulation.lua"]:1433: in function `turnRecursion'
[string "@TLDRMissions\simulation.lua"]:1462: in function <TLDRMissions\simulation.lua:27>
[string "@TLDRMissions\simulation.lua"]:1633: in function `Simulate'
[string "@TLDRMissions\combinations.lua"]:7: in function `func'
[string "@TLDRMissions\workhandler.lua"]:38: in function <TLDRMissions\workhandler.lua:23>

Locals:
follower = <table> {
 autoAttack = <table> {
 }
 maxHP = 838
 changeDamageDealtRaw = 0
 spells = <table> {
 }
 changeDamageDealtPercent = 100
 followerID = "0x000000002AD3A7F4"
 changeDamageTakenPercent = 100
 changeDamageTakenRaw = 0
 name = "Dreamweaver"
 boardIndex = 4
 baseAttack = 294
 buffs = <table> {
 }
 HP = 550
 thorns = <table> {
 }
}
spell = <table> {
 effects = <table> {
 }
 onCooldown = 0
 duration = 0
 cooldown = 0
 spellID = 15
}
effectIndex = nil
rngTargets = <table> {
 enemies_random_ally = 10
 enemies_random_enemy = -1
 followers_random_ally = -1
 followers_random_enemy = -1
}
hasTaunt = nil
overrideTarget = nil
effect = <table> {
 target = "furthest_enemy"
 type = "attack"
 attackPercent = 100
}
targets = <table> {
 1 = <table> {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
}
(for control) = 1
_ = 1
target = <table> {
 autoAttack = <table> {
 }
 changeDamageDealtRaw = 0
 maxHP = 6400
 spells = <table> {
 }
 changeDamageDealtPercent = 80
 boardIndex = 6
 changeDamageTakenPercent = 100
 changeDamageTakenRaw = 0
 name = "Grand Automaton"
 followerID = -1
 baseAttack = 195
 buffs = <table> {
 }
 HP = 2280
 thorns = <table> {
 }
}
damage = 294
(*temporary) = <function> defined @TLDRMissions\simulation.lua:6
(*temporary) = "Dreamweaver[4][550HP] attacks Grand Automaton[6][2280HP] for 294"
(*temporary) = "["
(*temporary) = "4"
(*temporary) = "]["
(*temporary) = "550"
(*temporary) = "HP] attacks "
(*temporary) = "Grand Automaton"
(*temporary) = "["
(*temporary) = "6"
(*temporary) = "]["
(*temporary) = "2280"
(*temporary) = "HP] for "
(*temporary) = "294"
(*temporary) = nil
(*temporary) = "script ran too long"
boardStateDefeat = <function> defined @TLDRMissions\simulation.lua:28
getTargets = <function> defined @TLDRMissions\simulation.lua:493
calculateDamage = <function> defined @TLDRMissions\simulation.lua:731
print = <function> defined @TLDRMissions\simulation.lua:6
checkThorns = <function> defined @TLDRMissions\simulation.lua:831
checkDeath = <function> defined @TLDRMissions\simulation.lua:816
registerBuff = <function> defined @TLDRMissions\simulation.lua:597

**Comment by teelolws** [comment]
Its a problem with this mission: https://www.wowhead.com/mission=2256/grandiose-designs#

Specifically this ability one of the enemy minions uses: https://www.wowhead.com/adventure-combatant-ability/mawsworn-ritual-229

"Ancient rites and runes protect a random ally, reducing their damage taken by $s1% for two turns."

The addon is testing every possible situation - every possible ally that could be targetted. I'll either need to make it more efficient, or splinter the "randomness" across separate simulations.

I'll think about what I can do. In the meantime, maybe try moving the minimum level slider so it doesn't try using low level followers on this level 60 Elite mission. Move it closer to 5 or even 1
![image](https://user-images.githubusercontent.com/49792789/163473875-7ef14e15-bf12-4607-9d04-bd195a5d8ebc.png)

**Comment by teelolws** [comment]
I pushed some changes today that should stop "timeouts" happening, at the cost of taking longer to simulate these missions. Let me know if the timeouts still happen.
