### ISSUE TITLE
[BUG] Finish Completed Missions button no longer work

### ISSUE THREAD

**Issue by czullo** [teelolws/TLDRMissions#194]
After 55 update buttons calculate/finish no longer work when pressed,

**Comment by teelolws** [comment]
Don't see why it wouldn't. I didn't change anything about it.

Sometimes the mission table just doesn't work properly. I have to walk away from the table and then walk back to it again. It happens with Venture Plans button, too.

**Comment by czullo** [comment]
I never experience this with TLDRMissions before. And after update to 055 all my settings are gone and cant start/finish missions.

**Comment by teelolws** [comment]
Have you got errors turned on? Getting an error?

**Comment by czullo** [comment]
no, how can i turn them on?

**Comment by teelolws** [comment]
`/console scriptErrors 1`

**Comment by zeenk** [comment]
Works just fine for me, im doing my missions atm

**Comment by zeenk** [comment]
Try disable all other addons?

**Comment by teelolws** [comment]
I found the problem. I didn't embed AceAddon-3.0. A lot of other addons have it already, so if you don't have an addon that already has AceAddon-3.0 you'll get an error.

**Comment by czullo** [comment]
i dont have any other addons.

Message: Interface\AddOns\TLDRMissions\guihandlers.lua:4: Cannot find a library instance of "AceAddon-3.0".
Time: Sat May 14 05:38:09 2022
Count: 1
Stack: Interface\AddOns\TLDRMissions\guihandlers.lua:4: Cannot find a library instance of "AceAddon-3.0".
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\TLDRMissions\libs\LibStub\LibStub.lua"]:23: in function `LibStub'
[string "@Interface\AddOns\TLDRMissions\guihandlers.lua"]:4: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "AceAddon-3.0"."

**Comment by teelolws** [comment]
[TLDRMissions.zip](https://github.com/teelolws/TLDRMissions/files/8692108/TLDRMissions.zip)

**Comment by teelolws** [comment]
Fix is up.

![image](https://user-images.githubusercontent.com/49792789/168409547-d0152565-66c1-4c57-93a1-881588757388.png)


Not changing the version number so it keeps using the results cache.
