### ISSUE TITLE
[BUG] Stygia rewards are not recognized

### ISSUE THREAD

**Issue by cpuritscher** [teelolws/TLDRMissions#196]
The addon does not recognize Stygia rewards. Probably because they are not a currency but an actual item (Condensed Stygia, itemID: 178040)

![grafik](https://user-images.githubusercontent.com/67310095/168413011-62a90ce3-11ee-4da9-9000-5f3470e87e09.png)

**Comment by teelolws** [comment]
Its coded to recognise the item Id for stygia. Check your follower level restrictions.

**Comment by cpuritscher** [comment]
My bad, I did not see the advanced tab yet. But it was not the follower level restriction, it was the anima restriction which defaults to 150. Thank you!

**Comment by teelolws** [comment]
Wasn't aware there were missions that cost more than 150. How much did it cost?

**Comment by penguinlust** [comment]
I've seen Stygia missions cost 200. There may be missions that are higher, but I've gotten into the habit of changing the setting since it always reverts to 150 every time the add on launches.

**Comment by teelolws** [comment]
> it always reverts to 150 every time the add on launches

hrm its not supposed to

**Comment by penguinlust** [comment]
Just updated to the latest, tried setting it to 250 and quit WoW. Relaunched and back to 150 (I see you confirmed). Also, the one that costs 200 is the level 66 Stygia mission -- doesn't show up often but it is there. Next time I see it I will put the title here.

**Comment by penguinlust** [comment]
More weird behavior. I can get less than 300 to stick as long as I don't max it out on other characters. Once I do it resets them all to 150. Need to play around with this.

**Comment by teelolws** [comment]
Yes the saved variable is set to treat 300 as the "default", which wipes the variable if you have it on the default. But the slider itsself is set to default to 150. So, if the saved variable is empty, it doesn't change the slider.

Other characters shouldn't affect it. The settings are saved on a per-character basis, unless you use the Profile tab to move them around.
