### ISSUE TITLE
Often followers are near dead after a mission - could it be improved?

### ISSUE THREAD

**Issue by Nillx** [teelolws/TLDRMissions#20]
Noticed that often my followers are dead or near dead when they come from a mission. Is there a way to somehow improve that?

**Comment by teelolws** [comment]
By default, the addon tries to send out missions using as few followers and troops as possible, for the lowest anima cost. If you want it to send more troops, for healthier followers, click Advanced and change that setting:

![image](https://user-images.githubusercontent.com/49792789/163472564-8a877593-e551-4277-ad4f-7a1efef4e172.png)
