### ISSUE TITLE
Mission simulations

### ISSUE THREAD

**Issue by Imna1975** [teelolws/TLDRMissions#200]
Mission Simulation sometimes take 20 minutes or more

**Comment by teelolws** [comment]
From the front page:

Q: The number of simulations is really high. Is it broken?

A: Some missions involve "randomness", such as spells that have a random target. When this happens, the addon could take a long time to find a way to guarantee success. If you would prefer the addon finds solutions more quickly, change some of the advanced settings. Perhaps lower the level restriction, so low level minions aren't tested on high level missions. Or perhaps change the option to always fill with troops.
