### ISSUE TITLE
[BUG] One mission not being sent out

### ISSUE THREAD

**Issue by zeenk** [teelolws/TLDRMissions#201]
This anima mission is not being sent out for me even tho I have anima selected and many 60 followers left that can beat it super easily with VP, bug? or am I missing something in my settings for it?

![2022-05-15_05-25-46](https://user-images.githubusercontent.com/68170439/168455817-3d9341d7-7a7c-40e1-9891-61af189154d7.png)
![2022-05-15_05-27-09](https://user-images.githubusercontent.com/68170439/168455852-ff5d813d-2dbb-4d0c-9d23-105d1db5fa8d.png)

**Comment by teelolws** [comment]
Was not aware you could get epic anima items from the table!

**Comment by zeenk** [comment]
They were added in 9.2 I believe

**Comment by teelolws** [comment]
[profiles.zip](https://github.com/teelolws/TLDRMissions/files/8694272/profiles.zip)
try this

**Comment by zeenk** [comment]
I'll try it but I already sent out that specific mission manually with VP but I might get it again on some other alt I still have left to send out missions on.

**Comment by teelolws** [comment]
Oh well. I'll release the patch and presume it works until told otherwise!

**Comment by zeenk** [comment]
Sounds good 👍

**Comment by zeenk** [comment]
Can confirm it works now 😌 
![2022-05-15_18-38-02](https://user-images.githubusercontent.com/68170439/168483768-68f04d17-95bc-4c46-9c56-739ff18cae60.png)
