### ISSUE TITLE
Only send 5 companions for Follower XP mission.

### ISSUE THREAD

**Issue by SyntaxLegend** [teelolws/TLDRMissions#205]
Only send Follower XP missions if there are five companions available.
TLDR version: 

Basically just iterating on the already "Special treatment for Follower XP Missions?", I have bonus follower XP missions high up in priority, but sometimes I only have 1-2 companions able to be sent out. It'd be an idea to skip the XP missions unless I have 5 under-leveled companions to send on it, instead of sending only 1 or 2 out on it.

**Comment by teelolws** [comment]
I might make it min 4 followers.
