### ISSUE TITLE
Hosting on other sites

### ISSUE THREAD

**Issue by kingreboot** [teelolws/TLDRMissions#207]
Love your addon so far, but as of Monday the 16th, Curseforge API v1 will go away and accesse to it with 3rd party manager like WoW.up will go away. If you be willing to add your addon to another host like Wago.io or wow interface that would be great. That or make your Github repo work with wow.up by setting it as a release. Thank you for the work you have done so far.

**Comment by teelolws** [comment]
I'm not hosting it on wago, wowup, or Github, due to not agreeing with the IP surrender conditions of their TOS. Wowinterface won't allow me to host there. So its a Curseforge exclusive until something changes.

**Comment by kingreboot** [comment]
why won't wowinerface let you host there?

**Comment by Frici42** [comment]
I don't wanna start a debate on the matter really, your addon, your choice. We shouldn't dictate where you'll host it.

But as kingreboot asked am definitely interested to hear why wowinterface doesn't allow you to host there specifically. 
Considering other addons are(or are getting) there it's interesting to know where the conflict comes from if you can share.

**Comment by teelolws** [comment]
I can't host on WoWI because one (or multiple) of the moderators has a personal issue with me. I tried to host a different addon there about 8 months ago, it was declined without reason or opportunity to appeal.

**Comment by Frici42** [comment]
oof Yeah, that doesn't sound good. I wonder if the situation over there changed but I guess I will be downloading it manually for now. Your work has gotten me running the damn mission tables again without it feeling like a total pain so pretty grateful for it 😅
