### ISSUE TITLE
[BUG] Lua error : Addon breaks permanently with "script ran too long" if simulations are still running (or maybe even just if the window is still open) when the game logs you out for inactivity

### ISSUE THREAD

**Issue by nzall** [teelolws/TLDRMissions#211]
I have a Kyrian Paladin with a full roster of 24 level 46-49 characters, the full Adventure Campaign finished, as well as the Covenant Campaign, the Korthia Campaign and the Zereth Mortis Campaign. Because of this, it can often take hundreds of thousands of simulations for everything to finish regardless of what settings I choose.

Today, I started the simulations right before I had dinner, and with cleaning up the kitchen it took me until well after I was logged out for inactivity to return. When I returned and logged back in, then started the simulations again, it would immediately error out with the below error. And I do mean immediately: the screen froze for about 5-10 seconds, and it would end the calculation and I would be unable to restart it until I reloaded my UI, at which point it would break in the same way when tried again. Because I wasn't around at the time I was logged out, I am unaware of whether the simulations were finished already at the time of logging out.

More importantly, this bug persisted through client restarts and through addon reinstalls with the Curseforge Client. In the end, I had to delete my SavedVariables and uninstall the addon, log in, log back out and install the addon fresh again before it would work again. 

3x TLDRMissions\workhandler.lua:64: script ran too long
[string "@TLDRMissions\workhandler.lua"]:64: in function <TLDRMissions\workhandler.lua:23>

Locals:
self = <unnamed> {
 0 = <userdata>
}
elapsed = 0.069000
workPerFrame = 8
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
 53 = <table> {
 }
 54 = <table> {
 }
 55 = <table> {
 }
 56 = <table> {
 }
 57 = <table> {
 }
 58 = <table> {
 }
 59 = <table> {
 }
 60 = <table> {
 }
 61 = <table> {
 }
 62 = <table> {
 }
 63 = <table> {
 }
 64 = <table> {
 }
 65 = <table> {
 }
 66 = <table> {
 }
 67 = <table> {
 }
 68 = <table> {
 }
 69 = <table> {
 }
 70 = <table> {
 }
 71 = <table> {
 }
 72 = <table> {
 }
 73 = <table> {
 }
 74 = <table> {
 }
 75 = <table> {
 }
 76 = <table> {
 }
 77 = <table> {
 }
 78 = <table> {
 }
 79 = <table> {
 }
 80 = <table> {
 }
 81 = <table> {
 }
 82 = <table> {
 }
 83 = <table> {
 }
 84 = <table> {
 }
 85 = <table> {
 }
 86 = <table> {
 }
 87 = <table> {
 }
 88 = <table> {
 }
 89 = <table> {
 }
 90 = <table> {
 }
 91 = <table> {
 }
 92 = <table> {
 }
 93 = <table> {
 }
 94 = <table> {
 }
 95 = <table> {
 }
 96 = <table> {
 }
 97 = <table> {
 }
 98 = <table> {
 }
 99 = <table> {
 }
 100 = <table> {
 }
 101 = <table> {
 }
 102 = <table> {
 }
 103 = <table> {
 }
 104 = <table> {
 }
 105 = <table> {
 }
 106 = <table> {
 }
 107 = <table> {
 }
 108 = <table> {
 }
 109 = <table> {
 }
 110 = <table> {
 }
 111 = <table> {
 }
 112 = <table> {
 }
 113 = <table> {
 }
 114 = <table> {
 }
 115 = <table> {
 }
 116 = <table> {
 }
 117 = <table> {
 }
 118 = <table> {
 }
 119 = <table> {
 }
 120 = <table> {
 }
 121 = <table> {
 }
 122 = <table> {
 }
 123 = <table> {
 }
 124 = <table> {
 }
 125 = <table> {
 }
 126 = <table> {
 }
 127 = <table> {
 }
 128 = <table> {
 }
 129 = <table> {
 }
 130 = <table> {
 }
 131 = <table> {
 }
 132 = <table> {
 }
 133 = <table> {
 }
 134 = <table> {
 }
 135 = <table> {
 }
 136 = <table> {
 }
 137 = <table> {
 }
 138 = <table> {
 }
 139 = <table> {
 }
 140 = <table> {
 }
 141 = <table> {
 }
 142 = <table> {
 }
 143 = <table> {
 }
 144 = <table> {
 }
 145 = <table> {
 }
 146 = <table> {
 }
 147 = <table> {
 }
 148 = <table> {
 }
 149 = <table> {
 }
 150 = <table> {
 }
 151 = <table> {
 }
 152 = <table> {
 }
 153 = <table> {
 }
 154 = <table> {
 }
 155 = <table> {
 }
 156 = <table> {
 }
 157 = <table> {
 }
 158 = <table> {
 }
 159 = <table> {
 }
 160 = <table> {
 }
 161 = <table> {
 }
 162 = <table> {
 }
 163 = <table> {
 }
 164 = <table> {
 }
 165 = <table> {
 }
 166 = <table> {
 }
 167 = <table> {
 }
 168 = <table> {
 }
 169 = <table> {
 }
 170 = <table> {
 }
 171 = <table> {
 }
 172 = <table> {
 }
 173 = <table> {
 }
 174 = <table> {
 }
 175 = <table> {
 }
 176 = <table> {
 }
 177 = <table> {
 }
 178 = <table> {
 }
 179 = <table> {
 }
 180 = <table> {
 }
 181 = <table> {
 }
 182 = <table> {
 }
 183 = <table> {
 }
 184 = <table> {
 }
 185 = <table> {
 }
 186 = <table> {
 }
 187 = <table> {
 }
 188 = <table> {
 }
 189 = <table> {
 }
 190 = <table> {
 }
 191 = <table> {
 }
 192 = <table> {
 }
 193 = <table> {
 }
 194 = <table> {
 }
 195 = <table> {
 }
 196 = <table> {
 }
 197 = <table> {
 }
 198 = <table> {
 }
 199 = <table> {
 }
 200 = <table> {
 }
 201 = <table> {
 }
 202 = <table> {
 }
 203 = <table> {
 }
 20

**Comment by teelolws** [comment]
The success/fail cache probably got too big. Won't be easy to fix.

**Comment by teelolws** [comment]
Next patch will have an adjustable simulation limit of 30,000. Enough that any reasonable combination of followers/troops should have been found, and not too much to overflow the results cache. Originally discussed here: https://github.com/teelolws/TLDRMissions/issues/132
