### ISSUE TITLE
[BUG] Lua error attempt to index global 'hasTaunt' (a nil value)

### ISSUE THREAD

**Issue by cpuritscher** [teelolws/TLDRMissions#216]
Message: Interface\AddOns\TLDRMissions\simulation.lua:596: attempt to index global 'hasTaunt' (a nil value)
Time: Tue May 17 06:11:53 2022
Count: 1
Stack: Interface\AddOns\TLDRMissions\simulation.lua:596: attempt to index global 'hasTaunt' (a nil value)
[string "@Interface\AddOns\TLDRMissions\simulation.lua"]:596: in function <Interface\AddOns\TLDRMissions\simulation.lua:591>
[string "@Interface\AddOns\TLDRMissions\simulation.lua"]:792: in function <Interface\AddOns\TLDRMissions\simulation.lua:694>
[string "@Interface\AddOns\TLDRMissions\simulation.lua"]:1146: in function <Interface\AddOns\TLDRMissions\simulation.lua:1081>
[string "@Interface\AddOns\TLDRMissions\simulation.lua"]:1155: in function <Interface\AddOns\TLDRMissions\simulation.lua:1081>
[string "@Interface\AddOns\TLDRMissions\simulation.lua"]:1155: in function `turnRecursion'
[string "@Interface\AddOns\TLDRMissions\simulation.lua"]:1162: in function <Interface\AddOns\TLDRMissions\simulation.lua:23>
[string "@Interface\AddOns\TLDRMissions\simulation.lua"]:1279: in function `Simulate'
[string "@Interface\AddOns\TLDRMissions\combinations.lua"]:7: in function `func'
[string "@Interface\AddOns\TLDRMissions\workhandler.lua"]:50: in function <Interface\AddOns\TLDRMissions\workhandler.lua:23>

Locals: follower = <table> {
 maxHP = 3795
 spells = <table> {
 }
 hasTaunt = <table> {
 }
 autoAttack = <table> {
 }
 boardIndex = 0
 name = "Kinessa the Absorbent"
 followerID = "0x000000005B25DF4E"
 baseAttack = 202
 buffs = <table> {
 }
 HP = 494
 thorns = <table> {
 }
}
spells = <table> {
 effects = <table> {
 }
 onCooldown = 1
 duration = 0
 cooldown = 1
 spellID = 316
}
rngTargets = nil
targetType = "closest_enemy"
overrideTarget = <table> {
 1 = <table> {
 }
}
(*temporary) = <function> defined @Interface\AddOns\TLDRMissions\simulation.lua:108
(*temporary) = <table> {
 maxHP = 3795
 spells = <table> {
 }
 hasTaunt = <table> {
 }
 autoAttack = <table> {
 }
 boardIndex = 0
 name = "Kinessa the Absorbent"
 followerID = "0x000000005B25DF4E"
 baseAttack = 202
 buffs = <table> {
 }
 HP = 494
 thorns = <table> {
 }
}
(*temporary) = "closest_enemy"
(*temporary) = nil
(*temporary) = nil
(*temporary) = 1
(*temporary) = <table> {
 1 = <table> {
 }
}
(*temporary) = 1
(*temporary) = <table> {
 maxHP = 4400
 spells = <table> {
 }
 autoAttack = <table> {
 }
 boardIndex = 5
 name = "Warped Pack Hunter"
 followerID = -3
 baseAttack = 255
 buffs = <table> {
 }
 HP = 3158
 thorns = <table> {
 }
}
(*temporary) = nil
(*temporary) = <table> {
 0 = <table> {
 }
 7 = <table> {
 }
 1 = <table> {
 }
 2 = <table> {
 }
 4 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 5 = <table> {
 }
 10 = <table> {
 }
 3 = <table> {
 }
 6 = <table> {
 }
 12 = <table> {
 }
 11 = <table> {
 }
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = "attempt to index global 'hasTaunt' (a nil value)"
getTargets = <function> defined @Interface\AddOns\TLDRMissions\simulation.lua:108
processSpell = <function> defined @Interface\AddOns\TLDRMissions\simulation.lua:510

Reproducable calculating "Currupted Builders"

**Comment by teelolws** [comment]
Thanks. -059b going up with which fixes this.
[TLDRMissions.zip](https://github.com/teelolws/TLDRMissions/files/8705088/TLDRMissions.zip)
