### ISSUE TITLE
[Request] Skip a mission

### ISSUE THREAD

**Issue by Zazou49** [teelolws/TLDRMissions#22]
**TLDR Version of your idea**
TLDR version: 9.2.016

**Slightly longer version**

Be able to skip a mission without uncheking categories. For example I have a mission level 49 without success (12k simulations).

**Comment by teelolws** [comment]
This is not something I want to add. It would interfere too much with the background processing of simulations.

I think it would be better to just click that Abort button then change the advanced settings. Require it to fill out all slots with troops:
![image](https://user-images.githubusercontent.com/49792789/163645573-eb9d6271-a0d2-47e7-b498-77e037a00092.png)

And drop the minimum follower level down so it doesn't waste time trying to simulate followers who are too low:
![image](https://user-images.githubusercontent.com/49792789/163645969-06a48324-fd46-4d41-85a2-431540970509.png)
