### ISSUE TITLE
New special treatment for follower xp missions is not sending followers

### ISSUE THREAD

**Issue by Rathaniel** [teelolws/TLDRMissions#223]
Wont send 2 of my followers. meatball and croman level 49 on this xp mission and i don't know why.
![tldr 1](https://user-images.githubusercontent.com/20883388/168914624-f00bf779-5dc3-4248-8b30-9d43eb5e2a12.jpg)
![tldr 2](https://user-images.githubusercontent.com/20883388/168914636-5b6eb617-e29e-437a-960e-af2f5e7af472.jpg)
![tldr 3](https://user-images.githubusercontent.com/20883388/168914646-8a951876-6a91-425c-a536-c95a44d2aa96.jpg)
![tldr 4](https://user-images.githubusercontent.com/20883388/168914650-0d697019-b636-45fe-954e-ba3c9277de4a.jpg)
.

Not sure where to post this sorry.

**Comment by teelolws** [comment]
Check the tooltip for the "Special treatment" button. It will only send if you have 4 or 5 followers available. Any less and its deemed a waste of a mission!

**Comment by Rathaniel** [comment]
Ah, i send them last after got my gold and mats etc. Yes will change to "most" when doing xp missions.
