### ISSUE TITLE
[BUG] Easiest mission does not select "easiest" mission

### ISSUE THREAD

**Issue by dapal-003** [teelolws/TLDRMissions#24]
I currently have two gold missions, a level 36 that takes 2.5 hours and gives 316 gold, the other mission is a level 58 that takes 7.5 hours and gives 360 gold. 
![image](https://cdn.astolfo.nl/z/eL5KmE.png)
![image](https://cdn.astolfo.nl/z/DYJFcN.png)
![image](https://cdn.astolfo.nl/z/yj7KRt.png)

With the "easiest" setting ticked, TL;DR starts to calculate for the level 58 mission first, then moving onto the level 36 as it had found no suitable match ups for the mission.

What I expect to happen is that the level 36 mission is calculated for first as it is easier to clear, with the level being way lower.

**Comment by teelolws** [comment]
When I first made that hardest/easiest option, I meant for it to only apply to the "any remaining missions" reward. But I can see why it should apply to everything. I'll change that in the next update.

**Comment by dapal-003** [comment]
Heyo, I just downloaded 017 and tested it out, it works for gold now but when it came to an anima mission it picked a higher level (48) over a lower level (36) mission

**Comment by teelolws** [comment]
Try this, lmk if it works
[TLDRMissions.zip](https://github.com/teelolws/TLDRMissions/files/8499770/TLDRMissions.zip)

**Comment by dapal-003** [comment]
Darn I already manually sent that mission out, I'll try it out the next time

**Comment by teelolws** [comment]
I'll publish it with 018 tomorrow if I don't find any problems with it.

**Comment by dapal-003** [comment]
I just tested with the two files in the zip replacing the ones in the folder but it did not seem to fix the issue. Here's a screenshot:
![image](https://cdn.astolfo.nl/z/ZNrq9n.png)
A little too wild is an anima mission that is lower level than Slime Drenched Crystals yet TLDR took the latter first

**Comment by teelolws** [comment]
Disregard the zip, try the one I uploaded to curse about an hour ago.

**Comment by dapal-003** [comment]
Just tested it with the curse version and it now properly takes the order from easiest to most difficult. Thank you so much, for your amazing and quick development 💗
