### ISSUE TITLE
[BUG] Material bag not being detected

### ISSUE THREAD

**Issue by dapal-003** [teelolws/TLDRMissions#28]
There is a pouch of photogenic provision that drops from the NF table that is not put in the "crafting materials cache" category. As it doesn't calculate a mission for it if the crafting materials cache box is ticked
![image](https://cdn.astolfo.nl/z/3DKweX.png)
The item id is 190178

**Comment by teelolws** [comment]
Yeah anything that doesn't have "Cache" in the name won't be in the list I collected. I'll have to add the other ones manually as I find them. I'll add this in the next update.

**Comment by teelolws** [comment]
Found these too. Will add in next patch

https://www.wowhead.com/items/miscellaneous/other/name:brokers'?filter=128;14;0
