### ISSUE TITLE
[BUG] Lua error - If you have a follower in the Maw you haven't picked up.

### ISSUE THREAD

**Issue by Fraktyl** [teelolws/TLDRMissions#30]
2x TLDRMissions\simulation.lua:586: attempt to concatenate field 'followerID' (a nil value)
[string "@TLDRMissions\simulation.lua"]:586: in function <TLDRMissions\simulation.lua:495>
[string "@TLDRMissions\simulation.lua"]:965: in function <TLDRMissions\simulation.lua:938>
[string "@TLDRMissions\simulation.lua"]:1029: in function <TLDRMissions\simulation.lua:1018>
[string "@TLDRMissions\simulation.lua"]:1449: in function <TLDRMissions\simulation.lua:1393>
[string "@TLDRMissions\simulation.lua"]:1436: in function <TLDRMissions\simulation.lua:1393>
[string "@TLDRMissions\simulation.lua"]:1458: in function <TLDRMissions\simulation.lua:1393>
[string "@TLDRMissions\simulation.lua"]:1458: in function <TLDRMissions\simulation.lua:1393>
[string "@TLDRMissions\simulation.lua"]:1458: in function <TLDRMissions\simulation.lua:1393>
[string "@TLDRMissions\simulation.lua"]:1458: in function <TLDRMissions\simulation.lua:1393>
[string "@TLDRMissions\simulation.lua"]:1436: in function <TLDRMissions\simulation.lua:1393>
[string "@TLDRMissions\simulation.lua"]:1458: in function <TLDRMissions\simulation.lua:1393>
[string "@TLDRMissions\simulation.lua"]:1458: in function <TLDRMissions\simulation.lua:1393>
[string "@TLDRMissions\simulation.lua"]:1458: in function <TLDRMissions\simulation.lua:1393>
[string "@TLDRMissions\simulation.lua"]:1458: in function <TLDRMissions\simulation.lua:1393>
[string "@TLDRMissions\simulation.lua"]:1436: in function `turnRecursion'
[string "@TLDRMissions\simulation.lua"]:1465: in function <TLDRMissions\simulation.lua:27>
[string "@TLDRMissions\simulation.lua"]:1636: in function `Simulate'
[string "@TLDRMissions\combinations.lua"]:7: in function `func'
[string "@TLDRMissions\workhandler.lua"]:38: in function <TLDRMissions\workhandler.lua:23>

Locals:
follower = <table> {
 name = "The Maw"
 boardIndex = 13
 baseAttack = 100
 buffs = <table> {
 }
 changeDamageDealtPercent = 100
 changeDamageDealtRaw = 0
}
targetType = "all_enemies"
rngTargets = nil
targets = <table> {
}
(*temporary) = <function> defined @TLDRMissions\simulation.lua:6
(*temporary) = "Error: no targets were found for "
(*temporary) = "all_enemies"
(*temporary) = " by follower "
(*temporary) = nil
(*temporary) = 10
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate field 'followerID' (a nil value)"
getClosestEnemy = <function> defined @TLDRMissions\simulation.lua:97
getAllEnemies = <function> defined @TLDRMissions\simulation.lua:439
getBackEnemies = <function> defined @TLDRMissions\simulation.lua:386
getFrontEnemies = <function> defined @TLDRMissions\simulation.lua:358
getCleaveEnemies = <function> defined @TLDRMissions\simulation.lua:129
getLineEnemies = <function> defined @TLDRMissions\simulation.lua:244
getConeEnemies = <function> defined @TLDRMissions\simulation.lua:290
getFurthestEnemy = <function> defined @TLDRMissions\simulation.lua:182
print = <function> defined @TLDRMissions\simulation.lua:6
field = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
}
getAllAllies = <function> defined @TLDRMissions\simulation.lua:427
getClosestAlly = <function> defined @TLDRMissions\simulation.lua:212
getAdjacentAllies = <function> defined @TLDRMissions\simulation.lua:328
getOtherAllies = <function> defined @TLDRMissions\simulation.lua:415
getFrontAllies = <function> defined @TLDRMissions\simulation.lua:451
getBackAllies = <function> defined @TLDRMissions\simulation.lua:477

---------------

I had Nerith Darkwing sitting in Torghast waiting for me to collect him.

**Comment by teelolws** [comment]
I didn't know that was possible. Did you already collect the follower?

**Comment by Fraktyl** [comment]
I had not.  I didn't click him when I ran Torghast and then he hangs out in the lobby.  I hearthed home after the run and left him there.  Completely user error, but just wanted to pass it along.

**Comment by teelolws** [comment]
[TLDRMissions.zip](https://github.com/teelolws/TLDRMissions/files/8500825/TLDRMissions.zip)

Can you try this, tell me if it fixes it?

**Comment by Fraktyl** [comment]
I actually picked him up now so I won't be able to test on that character.  Let me see if I can force one to spawn.  Will get back to you.

**Comment by teelolws** [comment]
I think I found the problem. It was nothing to do with that follower. 

It was this Maw mission (or a really similar mission) trying to hit your follower Najida while stealthed, causing an error:
![image](https://user-images.githubusercontent.com/49792789/163697607-99776f5c-2313-466d-87c4-de1ee3f6c631.png)

A fix will go up soon with 9.2-019
