### ISSUE TITLE
[BUG] A NF mission failed!

### ISSUE THREAD

**Issue by dapal-003** [teelolws/TLDRMissions#32]
[TLDRMissions.txt](https://github.com/teelolws/TLDRMissions/files/8502606/TLDRMissions.txt)

**Comment by teelolws** [comment]
Thanks. A fix will go up later today with 9.2-020.

**Comment by dapal-003** [comment]
I also had this Kyrian mission fail: [TLDRMissions.txt](https://github.com/teelolws/TLDRMissions/files/8502611/TLDRMissions.txt)

**Comment by teelolws** [comment]
![image](https://user-images.githubusercontent.com/49792789/163735853-d6ab5a7b-8766-4357-854e-ddc5120171a8.png)

It dealt Thorns damage back to Pelagos after it died. But other times I've seen this same interaction, it didn't. Blizzard are so inconsistent.

**Comment by dapal-003** [comment]
That is certainly annoying, I guess it'd be saver to assume that thorns damage will always be received

**Comment by teelolws** [comment]
On a different mission, Molako continuing to be a problem. When you place it on the board manually, it'll show "targets" where its "line attack" will hit. But the combat log shows something completely different. I have to see enough combat logs with Molako to know which target it is actually going to hit in each situation.
