### ISSUE TITLE
[BUG] A mission failed! Maldraxxus 

### ISSUE THREAD

**Issue by Nillx** [teelolws/TLDRMissions#34]
Maldraxxus mission failed

[TLDRMissions.txt](https://github.com/teelolws/TLDRMissions/files/8505986/TLDRMissions.txt)

**Comment by teelolws** [comment]
Found and fixed a number of bugs using this combat log, buffs being applied in the wrong order, buffs stacking incorrectly, buffs persisting after the minion died. 

I have some other combatlogs to check, then 9.2-021 will go up later today.
