### ISSUE TITLE
Reward Category: Campaign Missions

### ISSUE THREAD

**Issue by Goss444** [teelolws/TLDRMissions#37]
**TLDR Version of your idea**
TLDR version:  Make progression mission priority

**Slightly longer version**
The ability to select the progression missions to have higher priority and be chosen before other missions.

**Additional context**

**Comment by teelolws** [comment]
You mean the Campaign missions?

**Comment by Goss444** [comment]
Yes the Campaign missions, to try and knock these out as quickly as my followers are capable.

**Comment by teelolws** [comment]
I'll put that on my list for the future. Squashing errors and making the simulations more accurate is a priority for now.

**Comment by teelolws** [comment]
Coming in the next update, 9.2-028.
