### ISSUE TITLE
[BUG] Lua error

### ISSUE THREAD

**Issue by Rethyn** [teelolws/TLDRMissions#38]
Reinstalled .21 a couple times and still getting this error when I hit calculate.

1x TLDRMissions\simulation.lua:742: attempt to perform arithmetic on field 'changeDamageTakenPercent' (a nil value)
[string "@TLDRMissions\simulation.lua"]:742: in function <TLDRMissions\simulation.lua:715>
[string "@TLDRMissions\simulation.lua"]:896: in function <TLDRMissions\simulation.lua:870>
[string "@TLDRMissions\simulation.lua"]:1142: in function <TLDRMissions\simulation.lua:1048>
[string "@TLDRMissions\simulation.lua"]:1447: in function `turnRecursion'
[string "@TLDRMissions\simulation.lua"]:1487: in function <TLDRMissions\simulation.lua:27>
[string "@TLDRMissions\simulation.lua"]:1650: in function `Simulate'
[string "@TLDRMissions\combinations.lua"]:7: in function `func'
[string "@TLDRMissions\workhandler.lua"]:38: in function <TLDRMissions\workhandler.lua:23>

Locals:
attacker = <table> {
 maxHP = 3100
 spells = <table> {
 }
 autoAttack = <table> {
 }
 boardIndex = 11
 name = "Warden of Rituals"
 followerID = -1
 baseAttack = 170
 buffs = <table> {
 }
 HP = 3100
 thorns = <table> {
 }
}
defender = <table> {
 maxHP = 4080
 spells = <table> {
 }
 autoAttack = <table> {
 }
 boardIndex = 2
 name = "Rattlebag"
 followerID = "0x0000000022151DF1"
 baseAttack = 204
 buffs = <table> {
 }
 HP = 374
 thorns = <table> {
 }
}
attackPercent = 100
changeDamageTakenRaw = <table> {
 amount = 0
 lowestID = 999999
}
changeDamageDealtRaw = <table> {
 amount = 0
 lowestID = 999999
}
changeDamageTakenPercent = <table> {
 amount = 100
 lowestID = 999999
}
changeDamageDealtPercent = <table> {
 amount = 100
 lowestID = 999999
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
}
(for control) = 10
_ = 10
minion = <table> {
 maxHP = 4080
 spells = <table> {
 }
 autoAttack = <table> {
 }
 boardIndex = 2
 name = "Rattlebag"
 followerID = "0x0000000022151DF1"
 baseAttack = 204
 buffs = <table> {
 }
 HP = 374
 thorns = <table> {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 Rattlebag (shield)2 = <table> {
 }
 Rattlebag (thorns)2 = <table> {
 }
}
(for control) = "Rattlebag (shield)2"
_ = "Rattlebag (shield)2"
buff = <table> {
 duration = 2
 stacks = 1
 name = "Rattlebag (shield)"
 changeDamageTakenRaw = -123
 target = <table> {
 }
 ID = 2
 stackLimit = 1
}
(*temporary) = 100
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on field 'changeDamageTakenPercent' (a nil value)"
field = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
}

**Comment by teelolws** [comment]
Whoops! Uploading a fix now.

I made some big changes to the way buffs are stored/used today so some errors like this might slip through.
