### ISSUE TITLE
[BUG] Calculating misssions... forever.

### ISSUE THREAD

**Issue by czullo** [teelolws/TLDRMissions#39]
After updating to 21 i found bug. its calculationg like for 5 minutes theres only 1 calculation but it will no progress any further its just stuck... its on multiple alts, diffrent missions. Any way i can rollback to 20 verssion?
![WoWScrnShot_041922_054043](https://user-images.githubusercontent.com/13511496/163915804-e01adb1c-6617-4e69-afc7-77510d1c5268.jpg)
![WoWScrnShot_041922_054706](https://user-images.githubusercontent.com/13511496/163916311-6d63e461-aab8-4897-842e-11688deda54f.jpg)

**Comment by teelolws** [comment]
I'm also having issues with todays update. Going to rollback to yesterdays until I can get them sorted.

**Comment by teelolws** [comment]
I think you had the same issue as https://github.com/teelolws/TLDRMissions/issues/40 but you have error messages suppressed.
