### ISSUE TITLE
Selecting a specific mission from outside the list.

### ISSUE THREAD

**Issue by czullo** [teelolws/TLDRMissions#41]
TLDR version: Adding features that will allow selection mission from outside list. 

For example when You want to do camping mission or some other mission but don't want to add them to the list or don't want to calculate all remaining missions not from the list.

**Comment by teelolws** [comment]
Thats not really what I'm going for with this addon. If you want to target a specific mission, other addons already do this for you. This addon focuses on the rewards, not the missions.

**Comment by teelolws** [comment]
Campaign missions updates will be in this issue: https://github.com/teelolws/TLDRMissions/issues/37
