### ISSUE TITLE
Feature Discussion: Skip Calculating Mission Button

### ISSUE THREAD

**Issue by zaphon** [teelolws/TLDRMissions#45]
Some of the missions will cause the addon to calculate into the 100's of thousands of attempts, and sometimes even just hang (I've seen it just stop for no reason say in the 300k+ range instead of skipping the mission it's stuck on). Having the ability to just say "go ahead and skip this one" or set a max "time" limit per mission attempt would be handy.

**Comment by teelolws** [comment]
Its something I'm considering, but will require a rework of how I split the workload over time. In the meantime, I suggest adjusting the advanced filters. Start with lowering the slider, to say, 1 or 2, so it doesn't waste time trying level 10 followers on a level 60 mission.

**Comment by teelolws** [comment]
Okay going to add a SkipCalculations button in the next update, 9.2-023, later today. I haven't been able to do much testing with it, so be aware it might behave... weirdly. Especially if it was just about to calculate a success/failure when you clicked it. Or it might lock out other buttons / leave messages behind if its out of other missions to try. I'll get to all those as I see them happen.
