### ISSUE TITLE
Simulation Freezing after today update.

### ISSUE THREAD

**Issue by L30m4nc3r** [teelolws/TLDRMissions#47]
Simulation Freezing after today update and get error.
https://paste.ee/p/AvR4v
https://img001.prntscr.com/file/img001/N891DWh6TWCs9Gjqvifgtg.png

**Comment by L30m4nc3r** [comment]
I also propose an idea for the implementation of the addon. Add the possibility of a blacklist of tasks so that they are ignored. Since the addon tries to calculate some tasks and cannot calculate it.
![image](https://user-images.githubusercontent.com/710285/164031573-1c152ec9-2444-4afc-9b53-4dfce88cbbe1.png)
![image](https://user-images.githubusercontent.com/710285/164031617-e4a8e21d-48f4-42d5-8857-ae1effce0a64.png)
and so on indefinitely
https://wowhead.com/mission=2239/

**Comment by zaphon** [comment]
I've had this happen on a few different missions over the past 3 days, so it's not just the latest version.

**Comment by teelolws** [comment]
For the blacklist issue, I'm going to add a Skip button to force TLDR to stop calculating missions you don't want. For updates please move to this issue: https://github.com/teelolws/TLDRMissions/issues/45

**Comment by teelolws** [comment]
I think I've stamped out the freezing bug. If it happens again, make sure you aren't blocking error messages. If it freezes theres usually an Lua error with it, and I can't find the problem without the error.

Update should be going up within the hour with 9.2-023.
