### ISSUE TITLE
Suggestion: Ignore the EXP mission, if the followers is full max level.

### ISSUE THREAD

**Issue by BlueNightSky** [teelolws/TLDRMissions#5]
Suggestion: Ignore the Exp mission (only exp not exp item mission), if the followers is full max level.

**Comment by teelolws** [comment]
I'll look at making it an *option*. Some people might still want to clear them to make new missions appear.

**Comment by teelolws** [comment]
Added an option to treat Bonus Follower XP missions differently: if enabled they'll try to take <lv60 followers and take as many as possible.

![image](https://user-images.githubusercontent.com/49792789/162597516-96f5d360-ace0-4bad-ac56-c6c613bfec8b.png)

(coming in version 9.2-011)
