### ISSUE TITLE
[BUG] A mission failed! Necrolords

### ISSUE THREAD

**Issue by czullo** [teelolws/TLDRMissions#53]
Mission failed from Necrolords. Once again, thanks for great addon, and dont worry that it fails some mission. Keep it good work buddy.

[TLDRMissions.zip](https://github.com/teelolws/TLDRMissions/files/8531200/TLDRMissions.zip)

**Comment by teelolws** [comment]
Some issues there with attacks that "cleave". I fixed the attack order for this one but there will be more. Keep sending those combat logs in!
