### ISSUE TITLE
[BUG] A mission failed! Necrolord

### ISSUE THREAD

**Issue by Nillx** [teelolws/TLDRMissions#59]
Necrolord mission failed 
[TLDRMissions.txt](https://github.com/teelolws/TLDRMissions/files/8536060/TLDRMissions.txt)

**Comment by teelolws** [comment]
Thanks. A small mistake with the spell "Stolen Wards". Unfortunately, the fix missed todays release and will have to wait for 9.2-026.

**Comment by Nillx** [comment]
No worries. Also is it possible to add whats changed in the changelog when you release an update?

**Comment by teelolws** [comment]
I haven't really been writing down details of what I change. A lot of them are just minor tweaks to the spell settings, or how the simulator handles them. Essentially just minor improvements to the accuracy of its predictions. I could go Nintendo-style and put "General stability improvements to enhance the user's experience."? (lol)

**Comment by Nillx** [comment]
Fair enough! What about when you add a new option or feature?
