### ISSUE TITLE
Reject mission button

### ISSUE THREAD

**Issue by dapal-003** [teelolws/TLDRMissions#6]
**Is your feature request related to a problem? Please describe.**
Having the mission name displayed is a sort-of way of getting there, however you'd then need to compare it with the list to see where the mission is and then being able to see the rewards.

**Describe the solution you'd like**
Underneath `Mission:` I'd like to see the space for three lines to appear.
1. Follower xp, the xp the followers get (includes bonus follower xp)
2. (optional) reward 1
3. (optional) reward 2

**Describe alternatives you've considered**
Other ways of displaying it would be to copy the icons over, but I feel like it does not fit with the general UI theme and it'd make it a lot bigger. Another thing that can happen is to have tldr moved to the side and highlight the mission in the selection screen as it's calculating

**Additional context**
I feel that a "Skip this mission" button would accompany this feature really well so that if there is a particular item that you don't want or if the calculation is going on forever, you can skip it.

**Comment by teelolws** [comment]
For showing the rewards: I'll add this to the list. It'll take some thought about where to display the rewards.

For a skip button: this might cause some problems. While the addon is waiting for you to click the Start Mission button, it is still calculating your next mission. While it does that, it presumes the followers that are waiting to be sent will be unavailable for the remaining missions. So, sure, you can skip a mission, but if you do this, you'll have to start the calculations all over again if you want that follower set on a different mission. And I'll have to implement a way to remember that you didn't want that mission.

**Comment by teelolws** [comment]
Added in 9.2-009
