### ISSUE TITLE
Buff order of operations

### ISSUE THREAD

**Issue by czullo** [teelolws/TLDRMissions#62]
[Upload your Saved Variables here]
You can find your Saved Variables in your WoW folder, under WTF \ Account \ YOUR ACCOUNT \ YOUR REALM \ YOUR CHARACTER \ SavedVariables \ TLDRMissions.lua

Github won't allow you to upload a .lua file directly, but you can either .zip it up or just copy/paste the entire contents of the file here.
[TLDRMissions.zip](https://github.com/teelolws/TLDRMissions/files/8538606/TLDRMissions.zip)

**Comment by teelolws** [comment]
Going to have to compare this one against other combat logs before I make any changes. The results are different to what I've seen before.

Emaciated Etherwyrm[5] applied Herd Immunity to Starved Etherwyrm[6][1258HP].

Emaciated Etherwyrm[8] applied Herd Immunity to Starved Etherwyrm[6][1258HP].

Thats supposed to be -100% damage taken.

Meatball[3] applied Meatball Mad! to Meatball[3][1814HP].

That increases his damage by 306. But:

Meatball[3] cast Meatball Mad! at Starved Etherwyrm[6][1258HP] for 0  damage.

This time the buffs aren't applying in order. Or maybe new buffs no longer work if the damage is already zero?

**Comment by czullo** [comment]
Well i dont know blizz logic, but if enemy got buff to take -100% damage then buffing attacker(meatball) wont change this i suppose.

**Comment by teelolws** [comment]
Yeah its inconsistent with other combat logs I've seen though. I've seen ones reduce damage by 90%, then add 200, and the +200 didn't get reduced by 90%.

**Comment by teelolws** [comment]
Okay, new example:

    Blighted Conqueror[6] applied Defense of the Drust to Blighted Overseer[5][1550HP].

Reduced its damage taken by 50%.

    Meatball[0] applied Meatball Mad! to Meatball[0][864HP].

Increases its damage dealt by 318.

    Meatball[0] cast Meatball Mad! at Blighted Overseer[5][1289HP] for 182  damage.
