### ISSUE TITLE
Feature request: Show mission reward pre completed calculation

### ISSUE THREAD

**Issue by zeenk** [teelolws/TLDRMissions#69]
Would it be possible to show the rewards of the mission instantly instead of only when the mission is done calculating so it's easier to tell if I should skip a mission that is taking a very long time to calculate and just do it manually after the fast missions are done?

**Comment by teelolws** [comment]
Yeah why not.

![image](https://user-images.githubusercontent.com/49792789/164874464-d5a426b9-e530-4107-9dc0-687ed9fed690.png)


Try this:
[guihandlers.zip](https://github.com/teelolws/TLDRMissions/files/8546098/guihandlers.zip)
