### ISSUE TITLE
Add a title bar to the UI + movability

### ISSUE THREAD

**Issue by teelolws** [teelolws/TLDRMissions#71]

**Comment by Evolutious** [comment]
+1 to this request

Would love the option to clamp the window to the outside of the mission window (not overlapping) instead of it floating on top of it in the center.

**Comment by teelolws** [comment]
Its on my todo list, along with a few other UI and feature changes, but improving the accuracy is the highest priority.

**Comment by L30m4nc3r** [comment]
Please, when you update the addon, make a list of changes, it is very interesting to know what has been fixed and what has been implemented, I follow your work with special interest, but I do not understand what changes after each update. <3

**Comment by teelolws** [comment]
@L30m4nc3r 
> but I do not understand what changes after each update.

Every patch had at least one "accuracy" fix, which is the most important thing: lower failure rates with each patch --> less anima wasted on missions that don't succeed.

Half the time I don't even remember what I changed by the time I release it. I'm just a Large Corporate Conglomerate™ with Infinite Resources™ to spend on my Massive Development Team™ who totally keeps track of everything systematically because this is their full time job, they are dedicated to this project and nothing else!

**Comment by teelolws** [comment]
Title bar + movability in next version. You'll be able to click and drag from anywhere in the UI that isn't already a button cause I don't know how to restrict it to just the title bar.
