### ISSUE TITLE
[BUG] A mission failed! Necro

### ISSUE THREAD

**Issue by Nillx** [teelolws/TLDRMissions#76]
[TLDRMissions.txt](https://github.com/teelolws/TLDRMissions/files/8548662/TLDRMissions.txt)

Necrolord mission failed

**Comment by teelolws** [comment]
Thanks. Investigating this one found a significant bug with the way "thorns" or "reflect" damage was stored between simulations involving randomness. I had to do a fair bit of rework to fix it. I'll be doing some more testing, then will release it later today if I don't encounter any errors.
