### ISSUE TITLE
Translations needed: FPS slider

### ISSUE THREAD

**Issue by teelolws** [teelolws/TLDRMissions#82]
@BlueNightSky hi, I need some more translations please.

![image](https://user-images.githubusercontent.com/49792789/165002395-3fab6334-2f1a-40fa-a921-10f9c865b2d2.png)

I've added the empty templates to https://github.com/teelolws/TLDRMissions/blob/main/Translations/zhtw.lua

Please let me know when its done. Github didn't notify me when you committed directly last time for some reason, so I didn't realise it was done until too late.

**Comment by teelolws** [comment]
Also, going to add a title bar with the addon name and version. Do you think the name needs to be translated, or can I keep the English name?

**Comment by BlueNightSky** [comment]
I think the addon name keep English is ok!

**Comment by teelolws** [comment]
Thanks!
