### ISSUE TITLE
[BUG] Sim per frame slider

### ISSUE THREAD

**Issue by zeenk** [teelolws/TLDRMissions#83]
If you change the new sim slider and relog after it doesn't keep the changes to it.

Dunno if intended or not?

**Comment by teelolws** [comment]
Er. No. Thats not intended.

**Comment by teelolws** [comment]
Okay its just a visual bug. The setting is still being saved, and as long as you don't move the slider after a reload, it will use what you had it set to before the reload. I just forgot to make it update the slider when you reload.

I'll schedule a fix for the visual bug next patch.

**Comment by zeenk** [comment]
Works now with the 9.2-029 release :) thx
