### ISSUE TITLE
[BUG] Lua error

### ISSUE THREAD

**Issue by zeenk** [teelolws/TLDRMissions#84]
Message: Interface\AddOns\TLDRMissions\caching.lua:162: attempt to index field '?' (a nil value)
Time: Mon Apr 25 06:35:12 2022
Count: 1
Stack: Interface\AddOns\TLDRMissions\caching.lua:162: attempt to index field '?' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\TLDRMissions\caching.lua"]:162: in function `setResultCache'
[string "@Interface\AddOns\TLDRMissions\simulation.lua"]:1669: in function <Interface\AddOns\TLDRMissions\simulation.lua:1668>
[string "@Interface\AddOns\TLDRMissions\simulation.lua"]:1508: in function `func'
[string "@Interface\AddOns\TLDRMissions\workhandler.lua"]:41: in function <Interface\AddOns\TLDRMissions\workhandler.lua:23>

Locals:

**Comment by teelolws** [comment]
Not good. I wonder that a follower healed by 1HP between when you started calculating and when it found a solution.

I'll have a file for you to try in a minute.

**Comment by teelolws** [comment]
Can you try this?
[caching.zip](https://github.com/teelolws/TLDRMissions/files/8551675/caching.zip)

**Comment by zeenk** [comment]
Doesn't seem to be giving me the lua error now anymore but the simulation is taking a very long time for this mission "Warden's Wrath" on night fae alt. currently at 30k and still going up.

**Comment by zeenk** [comment]
Finally found a winning setup (hopefully) after 78k sims :P

**Comment by teelolws** [comment]
Unfortunately, thats a mission I still haven't seen on my own mission tables, so I haven't been able to check if it sims correctly!

**Comment by teelolws** [comment]
Going to push an update soon, cause I can't have that Lua error kicking around
