### ISSUE TITLE
[BUG] 9.2 missions

### ISSUE THREAD

**Issue by zeenk** [teelolws/TLDRMissions#85]
Don't know how to privately contact you on Github so trying here instead. This person made a fix for the 9.2 missions for the other mission table addon VenturePlan
https://github.com/hythloday/VenturePlanSoDMissions/issues/69

Maybe this information can help you someway to make the new missions finish calculate quicker?
Currently at 650k sims on the "Gorging Anima Thieves" mission for Venthyr and it's still going :/ have to do it manually instead with VenturePlan.

Hope it helps.

**Comment by teelolws** [comment]
I'm familiar with that. It was my starting point for building my own spell database. If TLDR is up to 650k sims on the mission and not finding a solution, there is probably a bug somewhere. But its a complicated issue and I can't really investigate it properly until I get offered the mission myself.

**Comment by zeenk** [comment]
I see, do you have an alt for each covenant that is above 16 in the campaign table lvls to be able to get the newest missions?

**Comment by teelolws** [comment]
I used to. I don't have Night Fae anymore 'cause I had to switch my main to Necrolord for the ability.

Something I could look at doing is creating a testing kit, where it will watch what missions you send out with Venture Plan, and capture the combatlog with the stats of the minions it sent out. That way I can at least have a combatlog, and the settings used before you sent it out, to compare against? You'd have to specifically toggle it on though by running a small bit of code. I have a lot of testing functions in the addon already that are locked behind code commands.

If I go down that route it will be a job for another day.

**Comment by zeenk** [comment]
Sounds good because with the community updated venture plan for 9.2 I have not had a single failed mission with it yet but I want this addon to be just as good as well because it will save so much time sending out all the missions on 44 alts everyday 😂 amazing work on it so far even if there is some failed missions here and there, hopefully it will work perfectly soonTM 👍

**Comment by teelolws** [comment]
If you want to hurry the fixes along, I have some code that checks what the addon thought your follower's HP would be at the end of the mission against what their HP actually is at the end of the mission. You have to manually turn it on, as I only intended people who know what they're doing to use it, by running: /run TLDRMissionsOptions.DEVTESTING = true

You'll get some false positives though. If a mission has any minion that has a "random" attack, then the addon doesn't (yet) save all their possible final health values, only the last calculated possibility. Another case is if it calculates, but you take a while to click the Send button and the minion heals up by 1HP from its natural healing-over-time. The addon doesn't do the simulation again when you go to send it out. It probably should.

**Comment by zeenk** [comment]
I'll check it out later today when I wake up, do I have to run that command on every alt?

**Comment by teelolws** [comment]
Yes. This addon has everything but the results cache as character-specific.

**Comment by zeenk** [comment]
So do I just run the command then hit the calculation button like normal and start sending out missions or how does it give u the information u need to fix bugged missions?

**Comment by teelolws** [comment]
Yes. It'll give the information when the missions come back. If the health doesn't match, it'll say something like "Discrepancy found for mission 2211", and puts everything into the saved variables for that character for me to check

**Comment by zeenk** [comment]
Alright I'll try that later today after my current missions I've sent out already are finished.

**Comment by zeenk** [comment]
[Devtesting.zip](https://github.com/teelolws/TLDRMissions/files/8557414/Devtesting.zip)

Ok I ran the devtesting command on all my 44 alts and these are the missions I got the "Discrepancy found for mission" message in chat on, some of the folders have multiple lua files, same mission report but from different alts, not sure if this was necessary or not but I did it anyway. I hope I did it correctly :P

**Comment by teelolws** [comment]
A lot of false positives in there, from a follower healing by 1HP between the simulation and when you sent it. Going to add a small bit of tolerance for the final HP, because thats just extra work for both of us to check the logs of a mission that was fine.

**Comment by zeenk** [comment]
Should I keep posting the devtesting folders here or make new bug report in the future? also is 1 lua report per mission enough or do u want all of them?

**Comment by teelolws** [comment]
Keep them coming but wait until the next patch for more. I've already picked up a number of fixes from your batch. I'm about halfway through them.

**Comment by zeenk** [comment]
Alright 👍

**Comment by teelolws** [comment]
Another one. https://www.wowhead.com/adventure-combatant-ability/power-of-domination-369 it says it deals damage every turn, but it only actually deals damage on the last turn right before the debuff expires. I have yet to see a DOT ability that works the way its described.

**Comment by teelolws** [comment]
Hmm. One of your logs has Dreamweaver + 4 troops in the lineup, but the combatlog has Dreamweaver + Sulanoom + 3 troops. Guess I need to add more checks around that Send Mission button, make damn sure the right followers are being sent.

**Comment by teelolws** [comment]
Okay, so, the new patch has been up for a couple of hours. Heres what we'll do with the discrepancy going forward.

I have a few separate posts about specific missions that have "randomness". For discrepancies with those missions, post them there. I'm looking for "patterns" in the combat logs, to see if they're truly random or not. More combat logs, more evidence of patterns!

But for all other missions that don't already have an issue about them, just make a new megapost issue.
