### ISSUE TITLE
[BUG] Tez'an targetting oddities.

### ISSUE THREAD

**Issue by stevietv** [teelolws/TLDRMissions#90]
[Upload your Saved Variables here]
You can find your Saved Variables in your WoW folder, under WTF \ Account \ YOUR ACCOUNT \ YOUR REALM \ YOUR CHARACTER \ SavedVariables \ TLDRMissions.lua

Github won't allow you to upload a .lua file directly, but you can either .zip it up or just copy/paste the entire contents of the file here.
[TLDRMissions.zip](https://github.com/teelolws/TLDRMissions/files/8556101/TLDRMissions.zip)

**Comment by teelolws** [comment]
Thanks. Theres something in this combatlog that doesn't make sense:

    Te'zan[1] cast Onslaught at Warped Orb Smasher[10][4004HP] for 448  damage.
    Te'zan[1] cast Onslaught at Warped Orb Smasher[11][1540HP] for 448  damage.

The description of the attack is:

     Tez'an rips and tears with his teeth, dealing $s1 Nature damage to all enemies in melee.

On the first couple of turns, he attacked all 4 of the front enemy minions. But then on this turn he attacks the two minions in the back instead?

I'll need to do some investigating on a Night Fae to fix this one, but I don't have a Night Fae character available right now. I'll get back to this one.

**Comment by teelolws** [comment]
Another one for the Tezan mystery.
[tezan.txt](https://github.com/teelolws/TLDRMissions/files/8597822/tezan.txt)

**Comment by teelolws** [comment]
[tezan.zip](https://github.com/teelolws/TLDRMissions/files/8598312/tezan.zip)

They have one thing in common: tezan is taunted. Suspect Tezan's spell is affected by taunt, when other spells don't appear to be. Have changed "get front enemies" to be affected by taunt, need to review if its only tezan or all "get front enemies" spells.
