### ISSUE TITLE
[BUG] Night fae mission failed!

### ISSUE THREAD

**Issue by Nillx** [teelolws/TLDRMissions#93]
Night fae mission failed. Should i delete the file after i report a failed mission? Noticing that its slowly increasing in size over time.
[TLDRMissions.txt](https://github.com/teelolws/TLDRMissions/files/8558332/TLDRMissions.txt)

**Comment by teelolws** [comment]
Nah. The addon will clean it out over time. When you send out that same mission again in the future, it will replace all the old data and delete the old combat log.

**Comment by teelolws** [comment]
Thanks. Was a weird rounding issue in Lua. 

    math.floor(170*0.7)

was outputting 118 when it should be 119. Had to rework the fraction to make it round properly.

Will be fixed in next patch later today.
