### ISSUE TITLE
[BUG] 1.5 gigabytes of RAM

### ISSUE THREAD

**Issue by L30m4nc3r** [teelolws/TLDRMissions#95]
1500 MB just stay afk in oribos 
https://cdn.discordapp.com/attachments/592321016449990658/968282266054819911/unknown.png

**Comment by teelolws** [comment]
Thats not RAM, thats space on your disk. Its in response to https://github.com/teelolws/TLDRMissions/issues/73 asking to cache the results of simulations to speed up the calculations next time. Theres a lot of missions, a lot of follower permutations, and a lot of space needed to store them all.

**Comment by teelolws** [comment]
I wonder that its something to do with the language you play in. In the cache, I'm using minion names for table keys. I didn't think about what would happen if the key isn't english characters though.

I'll have to think about a solution a bit more.

**Comment by teelolws** [comment]
A possible fix is going up now. Please let me know if it works!

**Comment by Nathazar** [comment]
I personally would rather have the addon run simulations as opposed to save all this data. I'm up to almost 500MB of cached memory. was at 200MB yesterday i feel that in the long run this will just eat up all my resources. Really appreciate the work you are doing on this addon, and i know it is impossible to please everyone.

**Comment by teelolws** [comment]
@Nathazar can you logout and check the size of your account-wide tldrmissions.lua saved variables file?

**Comment by Nathazar** [comment]
Alrighty Updated addon this morning. started out with little to no memory cached. Ran mission tables on 7 Characters 3NF 2K 1V 1M. After doing that went from about 15 MB cached to 100 MB Cached 
![Saved Variables File](https://user-images.githubusercontent.com/103943371/165287479-bf3e251e-63ab-4f0f-9e5f-29d73b603dea.png)

**Comment by teelolws** [comment]
Oof. Okay I'm working on some changes to cut down that filesize.

**Comment by teelolws** [comment]
Uploaded 9.2-032 which cuts down the cache size by removing unimportant data. I'll reexamine tomorrow whether the changes are enough, or if the feature needs to be cut.

**Comment by Nathazar** [comment]
Cool beans ill get that downloaded and see how it works! thanks again.

**Comment by teelolws** [comment]
The system wasn't working for me, so I moved the caching system further up the permutation chain.

Simple version: rather than storing "was Te'Zan + Blisswing + 2 troops a success?" about a billion times for all the permutations, instead it'll store: "is there a way to win with Te'Zan + Blisswing + unknown number of troops? ok what was it" just the once and skip over a bunch of loops when getting the cache.

Patch going up with 9.2-033
