### ISSUE TITLE
Show Anima cost of mission on TLDRMissions screen

### ISSUE THREAD

**Issue by czullo** [teelolws/TLDRMissions#97]
**TLDR Version of your idea**
TLDR version:  Show Anima cost of mission

**Slightly longer version**
Show Anima cost of mission on TLDRMission screen like under "Rewards" line or next to "start mission" "skip"

**Comment by teelolws** [comment]
Running out of room in this UI :X

**Comment by teelolws** [comment]
Ok, I put it next to the Skip button: 
![image](https://user-images.githubusercontent.com/49792789/165450138-777771d1-4914-45f8-94ce-bc6bce106748.png)
